const lessonData = {
    "01_AggressiveMonkeys.mp3": [{ 
        text: "Scientists wanted to see how a group learns violent rules. They put five chimpanzees in a cage. They hung delicious yellow bananas high up near the ceiling. When one monkey climbed up to get the bananas, scientists sprayed all five monkeys with very cold, uncomfortable water. After this happened a few times, the monkeys learned a new rule. The bananas caused the bad water. To stop the cold water, the group attacked any monkey that tried to reach the food. Then, the scientists changed the monkeys. They took one old monkey out and put a new monkey in. The new monkey didn't know about the cold water. It immediately tried to grab the bananas. The other four monkeys quickly attacked it and beat it up. The scientists slowly replaced all the original monkeys. Eventually, there were five completely new monkeys in the cage. The cold water was never used again. But whenever any monkey reached for the bananas, the group fiercely attacked it. The monkeys continued this violent behavior. They kept beating each other up simply because it was the established rule of their society. They followed the group rule blindly without knowing why it existed.",
        dict: { "wanted": "istedi", "see": "görmek", "learns": "öğrenir", "violent": "şiddetli", "rules": "kurallar", "put": "koydu", "hung": "astı", "delicious": "lezzetli", "yellow": "sarı", "high": "yüksek", "near": "yakın", "ceiling": "tavan", "climbed": "tırmandı", "get": "almak", "sprayed": "püskürttü", "cold": "soğuk", "uncomfortable": "rahatsız", "happened": "oldu", "learned": "öğrendi", "new": "yeni", "caused": "sebep oldu", "bad": "kötü", "stop": "durdurmak", "attacked": "saldırdı", "tried": "denedi", "reach": "ulaşmak", "food": "yiyecek", "changed": "değiştirdi", "took": "aldı", "did not know": "bilmiyordu", "immediately": "derhal", "grab": "yakalamak", "quickly": "hızlıca", "beat up": "dövmek", "slowly": "yavaşça", "replaced": "değiştirdi", "original": "orijinal/asıl", "eventually": "sonunda", "completely": "tamamen", "never": "asla", "used": "kullanıldı", "again": "tekrar", "reached": "ulaştı", "fierce": "şiddetli", "continued": "devam etti", "behavior": "davranış", "kept": "devam etti", "simply": "sadece", "established": "kurulmuş", "society": "toplum", "followed": "takip etti", "blindly": "körlemesine", "knowing": "bilerek", "existed": "var oldu" },
        questions: [ {q:"How many chimpanzees were in the cage?", a_en:"Five", a_tr:"Beş"}, {q:"What color were the bananas?", a_en:"Yellow", a_tr:"Sarı"}, {q:"What did scientists spray?", a_en:"Water", a_tr:"Su"}, {q:"Was the water cold?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the new monkeys know the rule?", a_en:"No", a_tr:"Hayır"}, {q:"Did they attack for bananas?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the rule followed blindly?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "02_AntSacrifice.mp3": [{ 
        text: "Ant colonies have a very strict society to survive dangerous times. Sometimes, there is absolutely no food available for the ants. The colony begins to starve and die. To save the group, one single ant will bravely sacrifice its own life. This special ant is always the oldest and weakest ant in the colony. Twenty young, strong warrior ants leave the nest with the old ant. They look for a tarantula, which is a huge, poisonous spider. When they find the spider, the young warrior ants hide behind rocks. The old ant slowly walks directly toward the dangerous spider. The hungry tarantula immediately sees the old ant and attacks. It uses all of its deadly poison to kill the single old ant. After the spider finishes its attack, it has no more poison left in its body. Suddenly, the twenty hiding warrior ants jump out. They easily attack and kill the defenseless spider. They carefully carry the giant spider's body back home to their hungry colony. Thanks to the brave sacrifice of the oldest ant, the whole colony gets enough food to survive the terrible shortage.",
        dict: { "have": "sahip olmak", "strict": "sert/katı", "survive": "hayatta kalmak", "dangerous": "tehlikeli", "available": "mevcut", "begins": "başlar", "starve": "açlıktan ölmek", "die": "ölmek", "save": "kurtarmak", "single": "tek", "bravely": "cesurca", "sacrifice": "feda etmek", "own": "kendi", "special": "özel", "always": "her zaman", "oldest": "en yaşlı", "weakest": "en zayıf", "young": "genç", "strong": "güçlü", "warrior": "savaşçı", "leave": "ayrılmak", "nest": "yuva", "look for": "aramak", "huge": "kocaman", "poisonous": "zehirli", "find": "bulmak", "hide": "saklanmak", "behind": "arkasında", "rocks": "kayalar", "slowly": "yavaşça", "walks": "yürür", "directly": "doğrudan", "hungry": "aç", "sees": "görür", "attacks": "saldırır", "uses": "kullanır", "deadly": "ölümcül", "kill": "öldürmek", "finishes": "bitirir", "left": "kalan", "suddenly": "aniden", "hiding": "saklanan", "jump out": "dışarı fırlamak", "easily": "kolayca", "defenseless": "savunmasız", "carefully": "dikkatlice", "carry": "taşımak", "giant": "dev", "gets": "alır", "enough": "yeterli", "terrible": "korkunç", "shortage": "kıtlık" },
        questions: [ {q:"Is ant society strict?", a_en:"Yes", a_tr:"Evet"}, {q:"Which ant is sacrificed?", a_en:"Oldest", a_tr:"En yaşlı"}, {q:"What animal do they look for?", a_en:"Tarantula", a_tr:"Tarantula"}, {q:"Is the spider poisonous?", a_en:"Yes", a_tr:"Evet"}, {q:"How many warrior ants hide?", a_en:"Twenty", a_tr:"Yirmi"}, {q:"Does the spider keep its poison?", a_en:"No", a_tr:"Hayır"}, {q:"Does the colony survive?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "03_BeeDemocracy.mp3": [{ 
        text: "Many people think only humans have elections, but some animals also use democratic systems. Honeybees are a perfect example of animal democracy. Even though the leader of the hive is called a queen, the bees make important decisions together. When their old hive gets too crowded, they need to build a new home. The scout bees explore different places. Then, they come back and vote on the best location by doing a special dance in the air. After they build the new hive, they must elect a brand new queen. They usually have three or four young candidates for the job. The bees hold a real, democratic election. The candidates try to get followers. The young bee with the most supporters officially becomes the new queen. The other bees do not fight or start a war over the results. They completely accept the new queen without any arguments. They respect the majority vote of the colony. This peaceful system helps the bees stay organized and strong. They show us that voting and accepting the final result is a very smart, natural way to successfully manage a large society.",
        dict: { "think": "düşünmek", "only": "sadece", "have": "sahip olmak", "democratic": "demokratik", "perfect": "mükemmel", "democracy": "demokrasi", "leader": "lider", "called": "adlandırılan", "queen": "kraliçe", "make": "yapmak", "important": "önemli", "together": "birlikte", "old": "eski", "crowded": "kalabalık", "need": "ihtiyaç duymak", "build": "inşa etmek", "new": "yeni", "explore": "keşfetmek", "different": "farklı", "places": "yerler", "come back": "geri gelmek", "vote": "oy vermek", "best": "en iyi", "special": "özel", "must": "zorunda olmak", "elect": "seçmek", "young": "genç", "candidates": "adaylar", "hold": "tutmak/yapmak", "real": "gerçek", "try": "denemek", "followers": "takipçiler", "officially": "resmen", "becomes": "olur", "fight": "savaşmak", "war": "savaş", "completely": "tamamen", "accept": "kabul etmek", "without": "olmaksızın", "respect": "saygı duymak", "peaceful": "huzurlu", "stay": "kalmak", "organized": "organize", "strong": "güçlü", "show": "göstermek", "final": "son", "smart": "akıllı", "natural": "doğal", "successfully": "başarıyla", "manage": "yönetmek", "large": "büyük" },
        questions: [ {q:"Is a bee hive a democracy?", a_en:"Yes", a_tr:"Evet"}, {q:"What do scout bees do?", a_en:"Explore", a_tr:"Keşfetmek"}, {q:"How do bees vote?", a_en:"Dance", a_tr:"Dans"}, {q:"How many queen candidates?", a_en:"Four", a_tr:"Dört"}, {q:"Do the bees fight over results?", a_en:"No", a_tr:"Hayır"}, {q:"What does the system help?", a_en:"Organization", a_tr:"Organizasyon"}, {q:"Is voting natural for bees?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "04_BulletEatingSnakes.mp3": [{ 
        text: "In the wild animal world, having incredibly fast reflexes is usually a very good thing. Snakes are a great example. A snake's reaction time is extremely fast. It takes only a fraction of a second for them to react to danger. This makes them one of the absolute quickest animals in nature. However, sometimes being too fast and aggressive can actually be a terrible mistake. Imagine a cowboy riding a horse in the desert. Suddenly, a dangerous rattlesnake appears on the ground. The cowboy quickly pulls out his gun and shoots the snake. You might think the bullet is too fast for the snake. But here is the amazing truth: the snake's reflex is actually faster than the bullet. The snake clearly sees the fast bullet coming toward its head. Instead of moving away to save its life, the aggressive snake thinks the bullet is a small animal. It quickly tries to bite the bullet. Because of this angry reflex, the bullet goes straight into its mouth and kills it. If the snake simply moved out of the way, it would live. Its own aggressive reaction causes its tragic death.",
        dict: { "wild": "vahşi", "incredibly": "inanılmaz derecede", "fast": "hızlı", "reflexes": "refleksler", "usually": "genellikle", "good": "iyi", "great": "harika", "reaction": "reaksiyon", "extremely": "son derece", "react": "tepki vermek", "danger": "tehlike", "absolute": "mutlak", "quickest": "en hızlı", "nature": "doğa", "aggressive": "agresif", "actually": "aslında", "terrible": "korkunç", "mistake": "hata", "imagine": "hayal et", "riding": "binmek", "horse": "at", "desert": "çöl", "dangerous": "tehlikeli", "appears": "görünür", "quickly": "hızlıca", "shoots": "ateş eder", "bullet": "mermi", "amazing": "şaşırtıcı", "truth": "gerçek", "clearly": "açıkça", "sees": "görür", "coming": "gelen", "save": "kurtarmak", "life": "hayat", "thinks": "düşünür", "small": "küçük", "bite": "ısırmak", "angry": "öfkeli", "straight": "doğruca", "kills": "öldürür", "simply": "sadece", "live": "yaşamak", "own": "kendi", "causes": "sebep olur", "tragic": "trajik", "death": "ölüm" },
        questions: [ {q:"Is a snake's reflex fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Where is the cowboy?", a_en:"Desert", a_tr:"Çöl"}, {q:"Does the cowboy shoot?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the reflex faster than the bullet?", a_en:"Yes", a_tr:"Evet"}, {q:"What does the snake think the bullet is?", a_en:"Animal", a_tr:"Hayvan"}, {q:"Where does the bullet go?", a_en:"Mouth", a_tr:"Ağız"}, {q:"Does the snake die?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "05_SealsAndDolphins.mp3": [{ 
        text: "Seals and dolphins live in the exact same ocean environment and eat the exact same kind of fish. However, they have completely different hunting strategies. Seals usually live together in large groups, but they act very selfishly. When a group of seals finds a lot of fish, every seal jumps into the water at the same time. They all try to aggressively catch as much food as possible for themselves. This crazy chaos scares the fish away quickly. Because of their selfish actions, the seals only catch a few fish. On the other hand, dolphins are incredibly smart and organized. When dolphins find fish, they work together as a perfect team. They swim in tight circles around the fish so the fish cannot escape. The weakest or youngest dolphins eat first. Then, they slowly switch places with the other dolphins. They take turns eating and swimming in circles. They continue this organized teamwork until every dolphin gets a fair share of food. If the greedy seals learned to work together patiently like the smart dolphins, they would easily catch much more food for their entire group.",
        dict: { "live": "yaşamak", "exact": "tam/aynı", "same": "aynı", "eat": "yemek", "kind": "tür", "completely": "tamamen", "different": "farklı", "hunting": "avlanma", "usually": "genellikle", "together": "birlikte", "large": "büyük", "act": "davranmak", "selfishly": "bencilce", "finds": "bulur", "jumps": "atlar", "aggressively": "agresifçe", "catch": "yakalamak", "possible": "mümkün", "themselves": "kendileri", "crazy": "çılgın", "chaos": "kaos", "scares": "korkutur", "quickly": "hızlıca", "selfish": "bencil", "only": "sadece", "few": "az", "smart": "akıllı", "organized": "organize", "work": "çalışmak", "perfect": "mükemmel", "team": "ekip", "swim": "yüzmek", "tight": "sıkı", "around": "etrafında", "escape": "kaçmak", "weakest": "en zayıf", "youngest": "en genç", "first": "ilk", "slowly": "yavaşça", "switch": "değiştirmek", "take turns": "sırayla yapmak", "continue": "devam etmek", "teamwork": "ekip çalışması", "fair": "adil", "greedy": "açgözlü", "patiently": "sabırla", "easily": "kolayca", "entire": "tüm" },
        questions: [ {q:"Do seals and dolphins eat fish?", a_en:"Yes", a_tr:"Evet"}, {q:"Are seals selfish?", a_en:"Yes", a_tr:"Evet"}, {q:"Do seals catch many fish?", a_en:"No", a_tr:"Hayır"}, {q:"Are dolphins organized?", a_en:"Yes", a_tr:"Evet"}, {q:"Who eats first in a dolphin group?", a_en:"Weakest", a_tr:"En zayıf"}, {q:"Do dolphins swim in circles?", a_en:"Yes", a_tr:"Evet"}, {q:"Are seals greedy?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "06_CleverOctopus.mp3": [{ 
        text: "Scientists believe the octopus is probably the most intelligent animal in the ocean. They did a special experiment to test animal intelligence. They took a very smart dog, a smart chimpanzee, and an octopus. They made all three animals very hungry. Then, they put delicious food inside a plastic bottle with a tight cap. The dog and the chimpanzee tried hard, but they could not open the bottle. They gave up after a few hours of trying. However, the clever octopus used its strong arms to unscrew the plastic cap. It opened the bottle in half an hour and ate the food. The next time the scientists gave the same bottle to the octopus, it opened the cap in only twenty seconds. But the most amazing part happened next. This smart octopus actually taught other octopuses how to open the bottles. Within three days, all the other octopuses easily opened their bottles in twenty seconds. Unfortunately, the average octopus only lives for about three short years. If these incredibly smart creatures lived much longer lives, they might build a complex, advanced civilization at the bottom of the sea.",
        dict: { "believe": "inanmak", "probably": "muhtemelen", "most": "en", "intelligent": "zeki", "did": "yaptı", "special": "özel", "test": "test etmek", "took": "aldı", "smart": "akıllı", "made": "yaptı", "hungry": "aç", "put": "koydu", "delicious": "lezzetli", "plastic": "plastik", "tight": "sıkı", "tried": "denedi", "hard": "zor", "could not": "yapamadı", "open": "açmak", "gave up": "vazgeçti", "trying": "denemek", "clever": "zeki", "used": "kullandı", "strong": "güçlü", "unscrew": "vidayı açmak", "opened": "açtı", "ate": "yedi", "gave": "verdi", "same": "aynı", "seconds": "saniyeler", "amazing": "şaşırtıcı", "happened": "oldu", "actually": "aslında", "taught": "öğretti", "others": "diğerleri", "easily": "kolayca", "unfortunately": "maalesef", "average": "ortalama", "lives": "yaşar", "short": "kısa", "incredibly": "inanılmaz derecede", "longer": "daha uzun", "build": "inşa etmek", "complex": "karmaşık", "advanced": "gelişmiş", "bottom": "dip" },
        questions: [ {q:"Which animal is most intelligent?", a_en:"Octopus", a_tr:"Ahtapot"}, {q:"What was inside the bottle?", a_en:"Food", a_tr:"Yiyecek"}, {q:"Did the dog open it?", a_en:"No", a_tr:"Hayır"}, {q:"How long did the octopus take first?", a_en:"Half hour", a_tr:"Yarım saat"}, {q:"How long the second time?", a_en:"Twenty seconds", a_tr:"Yirmi saniye"}, {q:"Did it teach others?", a_en:"Yes", a_tr:"Evet"}, {q:"How long do they live?", a_en:"Three years", a_tr:"Üç yıl"} ]
    }],

    "07_CrabMentality.mp3": [{ 
        text: "Just like some human beings, crabs often show a very negative and jealous behavior. When a single crab is put alone inside a basket, it can easily climb the sides. It quickly reaches the top and successfully escapes to freedom. However, the situation changes completely when there are two or more crabs in the same basket. When one brave crab tries to climb up toward the top, the other crabs become aggressive. They actively reach up and pull the climbing crab back down to the bottom. Instead of helping each other escape the trap, they constantly sabotage each other. Their internal jealousy makes sure that nobody ever escapes the basket. This strange behavior is incredibly reliable. Fishermen all over the world know about this natural habit. They never put a lid on their crab baskets because they know the crabs will happily keep each other trapped inside forever. This extremely self-defeating pattern created the famous human concept called 'crab mentality.' It describes jealous people who try to pull down anyone who becomes successful, simply because they are envious of their progress.",
        dict: { "show": "göstermek", "negative": "negatif", "jealous": "kıskanç", "behavior": "davranış", "single": "tek", "alone": "yalnız", "easily": "kolayca", "climb": "tırmanmak", "quickly": "hızlıca", "reaches": "ulaşır", "top": "üst", "successfully": "başarıyla", "escapes": "kaçar", "freedom": "özgürlük", "changes": "değişir", "completely": "tamamen", "brave": "cesur", "tries": "dener", "aggressive": "agresif", "actively": "aktifçe", "pull": "çekmek", "bottom": "dip", "helping": "yardım etmek", "trap": "tuzak", "constantly": "sürekli", "sabotage": "sabotaj etmek", "internal": "içsel", "jealousy": "kıskançlık", "makes sure": "emin olur", "strange": "garip", "reliable": "güvenilir", "know": "bilmek", "natural": "doğal", "habit": "alışkanlık", "never": "asla", "happily": "mutlulukla", "keep": "tutmak", "trapped": "kapana kısılmış", "forever": "sonsuza dek", "extremely": "son derece", "created": "yarattı", "famous": "ünlü", "successful": "başarılı", "simply": "sadece", "envious": "kıskanç", "progress": "ilerleme" },
        questions: [ {q:"Can a single crab escape?", a_en:"Yes", a_tr:"Evet"}, {q:"Are crabs jealous?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they pull each other down?", a_en:"Yes", a_tr:"Evet"}, {q:"Do fishermen use lids?", a_en:"No", a_tr:"Hayır"}, {q:"Is this behavior reliable?", a_en:"Yes", a_tr:"Evet"}, {q:"What is the concept called?", a_en:"Crab mentality", a_tr:"Yengeç zihniyeti"}, {q:"Does jealousy stop progress?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "08_DogsInSubway.mp3": [{ 
        text: "Moscow is a very big city with a famous subway system. There are also about thirty-five thousand stray dogs living in the city. These dogs do not have homes or owners. Most of them live far away from the busy city center, in the quiet suburbs. But there is not enough food in the suburbs for all these hungry dogs. So, the smart dogs have learned to use the public subway trains. They clearly understand the different train lines and the daily schedules. Every morning, they enter the stations and take the train downtown with the human workers. They spend the day finding food in the busy city streets. In the evening, they take the correct train back to their quiet suburban homes. The people in Moscow are usually very nice to these smart dogs. The dogs have learned excellent public manners. They politely lie down on the floor between the passenger seats. They never bark loudly or bother anyone on the train. Because they are so quiet and polite, the humans never complain about sharing their morning commute with these amazing animal passengers.",
        dict: { "famous": "ünlü", "living": "yaşayan", "homes": "evler", "owners": "sahipler", "busy": "meşgul", "quiet": "sessiz", "enough": "yeterli", "hungry": "aç", "smart": "akıllı", "learned": "öğrendi", "use": "kullanmak", "clearly": "açıkça", "understand": "anlamak", "different": "farklı", "daily": "günlük", "enter": "girmek", "take": "almak", "human": "insan", "spend": "harcamak", "finding": "bulma", "streets": "sokaklar", "correct": "doğru", "nice": "nazik", "excellent": "mükemmel", "manners": "görgü kuralları", "politely": "kibarca", "lie down": "uzanmak", "loudly": "yüksek sesle", "bother": "rahatsız etmek", "polite": "kibar", "complain": "şikayet etmek", "sharing": "paylaşmak", "amazing": "şaşırtıcı" },
        questions: [ {q:"In which city do the dogs live?", a_en:"Moscow", a_tr:"Moskova"}, {q:"How many stray dogs are there?", a_en:"Thirty five thousand", a_tr:"Otuz beş bin"}, {q:"Do they have owners?", a_en:"No", a_tr:"Hayır"}, {q:"Where do they live?", a_en:"Suburbs", a_tr:"Banliyöler"}, {q:"What do they use to go downtown?", a_en:"Subway", a_tr:"Metro"}, {q:"Are the dogs polite?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they bark on the train?", a_en:"No", a_tr:"Hayır"} ]
    }],

    "09_EmpathicMouse.mp3": [{ 
        text: "Many people think that only humans can understand the feelings of others. But scientists recently discovered that simple mice can actually feel empathy too. In an interesting experiment, scientists put one small mouse in a tight, uncomfortable cage. They made this mouse very hungry. Then, they put a second, free mouse into the same room. The free mouse saw the trapped animal. It immediately started trying to help. After some hard work, it finally opened the cage door and released the hungry mouse. The next day, the scientists repeated the exact same test. They put a brand new hungry mouse in the tight cage. Then, they brought back the very first mouse—the one that had been trapped the day before—and put it in the room. This mouse instantly ran to the cage. It quickly worked to set the new mouse free. It did this without any hesitation. The mouse clearly remembered the terrible feeling of being trapped and hungry. It felt genuine sadness for the new prisoner. This proves that animals can share emotional pain and actively try to help each other survive.",
        dict: { "understand": "anlamak", "feelings": "duygular", "recently": "son zamanlarda", "discovered": "keşfetti", "simple": "basit", "actually": "aslında", "feel": "hissetmek", "empathy": "empati", "interesting": "ilginç", "small": "küçük", "tight": "sıkı", "uncomfortable": "rahatsız", "made": "yaptı", "hungry": "aç", "free": "özgür", "saw": "gördü", "trapped": "kapana kısılmış", "immediately": "derhal", "started": "başladı", "trying": "deneme", "help": "yardım etmek", "hard": "zor", "finally": "sonunda", "opened": "açtı", "released": "serbest bıraktı", "repeated": "tekrarladı", "new": "yeni", "brought back": "geri getirdi", "first": "ilk", "instantly": "anında", "worked": "çalıştı", "without": "olmaksızın", "clearly": "açıkça", "remembered": "hatırladı", "terrible": "korkunç", "genuine": "gerçek/hakiki", "sadness": "üzüntü", "proves": "kanıtlar", "share": "paylaşmak", "emotional": "duygusal", "actively": "aktifçe", "survive": "hayatta kalmak" },
        questions: [ {q:"Can mice feel empathy?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the cage comfortable?", a_en:"No", a_tr:"Hayır"}, {q:"Did the free mouse help?", a_en:"Yes", a_tr:"Evet"}, {q:"What did the free mouse open?", a_en:"Door", a_tr:"Kapı"}, {q:"Did the first mouse remember the feeling?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it hesitate to help?", a_en:"No", a_tr:"Hayır"}, {q:"Do mice share emotional pain?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "10_FearfulMice.mp3": [{ 
        text: "People often believe that mice are naturally born with a deep fear of cats. But in reality, this is not true. Mice actually learn this fear from their society, and the fear quickly spreads among them. Fear is a contagious emotion. Scientists did a test to prove this. They put a large, aggressive cat in a glass box. They put a laboratory mouse in another glass box next to it. When they opened the curtain, the angry cat tried to attack. The laboratory mouse showed absolutely no fear at all. It had never seen a cat in its entire life. Two hours later, the scientists put a wild street mouse next to the lab mouse. They opened the curtain again. The cat aggressively tried to catch them. The wild street mouse was terrified and quickly ran away to hide. Suddenly, the calm laboratory mouse also started running away in terror. The lab mouse learned to be afraid simply by watching the other mouse's panic. It learned the rules of survival and prejudice directly from its neighbor, proving that social fears are taught, not born.",
        dict: { "believe": "inanmak", "born": "doğmuş", "deep": "derin", "fear": "korku", "true": "doğru", "actually": "aslında", "learn": "öğrenmek", "quickly": "hızlıca", "spreads": "yayılır", "contagious": "bulaşıcı", "emotion": "duygu", "did": "yaptı", "prove": "kanıtlamak", "large": "büyük", "aggressive": "agresif", "opened": "açtı", "angry": "öfkeli", "tried": "denedi", "attack": "saldırmak", "showed": "gösterdi", "never": "asla", "entire": "tüm", "wild": "vahşi", "aggressively": "agresifçe", "catch": "yakalamak", "terrified": "dehşete düşmüş", "ran away": "kaçtı", "hide": "saklanmak", "suddenly": "aniden", "calm": "sakin", "learned": "öğrendi", "afraid": "korkmuş", "simply": "sadece", "watching": "izleyerek", "panic": "panik", "survival": "hayatta kalma", "taught": "öğretildi" },
        questions: [ {q:"Are mice born afraid of cats?", a_en:"No", a_tr:"Hayır"}, {q:"Is fear contagious?", a_en:"Yes", a_tr:"Evet"}, {q:"Where was the cat?", a_en:"Glass box", a_tr:"Cam kutu"}, {q:"Did the lab mouse feel fear first?", a_en:"No", a_tr:"Hayır"}, {q:"Who was next to the lab mouse later?", a_en:"Street mouse", a_tr:"Sokak faresi"}, {q:"Did the street mouse panic?", a_en:"Yes", a_tr:"Evet"}, {q:"Are social fears taught?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "11_FosterSquirrels.mp3": [{ 
        text: "Canadian squirrels are solitary animals. Normally, animals that live alone are very selfish. But female Canadian squirrels are incredibly different and special. Sometimes, baby squirrels lose their parents in the dangerous forest. When a female squirrel finds these poor, lonely orphans, she will bravely adopt them. She takes care of them like her own babies. The male squirrels are usually very angry about sharing their food, but the loving females persuade their partners to accept the new babies. This incredible kindness is never forgotten. When the orphaned babies grow up, they remember the mother who saved their lives. To show their deep gratitude, the young squirrels collect many extra nuts. They bring this extra food back to their foster mother as a beautiful way to say thank you for her love and protection.",
        dict: { "solitary": "yalnız yaşayan", "normally": "normalde", "live": "yaşamak", "alone": "yalnız", "selfish": "bencil", "female": "dişi", "incredibly": "inanılmaz derecede", "different": "farklı", "special": "özel", "sometimes": "bazen", "baby": "bebek", "lose": "kaybetmek", "parents": "ebeveynler", "dangerous": "tehlikeli", "finds": "bulur", "poor": "fakir/zavallı", "lonely": "yalnız", "orphans": "yetimler", "bravely": "cesurca", "adopt": "evlat edinmek", "takes care": "bakmak/ilgilenmek", "own": "kendi", "male": "erkek", "usually": "genellikle", "angry": "öfkeli", "sharing": "paylaşma", "loving": "sevgi dolu", "persuade": "ikna etmek", "partners": "ortaklar", "accept": "kabul etmek", "incredible": "inanılmaz", "kindness": "nezaket", "forgotten": "unutulmuş", "grow up": "büyümek", "remember": "hatırlamak", "saved": "kurtardı", "show": "göstermek", "deep": "derin", "gratitude": "minnettarlık", "young": "genç", "collect": "toplamak", "extra": "fazla", "bring": "getirmek", "foster": "koruyucu/üvey", "beautiful": "güzel", "protection": "koruma" },
        questions: [ {q:"Are Canadian squirrels social animals?", a_en:"No", a_tr:"Hayır"}, {q:"Do solitary animals usually share?", a_en:"No", a_tr:"Hayır"}, {q:"What do female squirrels find?", a_en:"Orphans", a_tr:"Yetimler"}, {q:"Who is angry about sharing food?", a_en:"Males", a_tr:"Erkekler"}, {q:"Is the kindness forgotten?", a_en:"No", a_tr:"Hayır"}, {q:"What do grown babies bring back?", a_en:"Nuts", a_tr:"Kuruyemişler"}, {q:"Is it a beautiful way to say thank you?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "12_FriedHornets.mp3": [{ 
        text: "Japanese Giant Hornets are terrible, dangerous insects. A hornet's sting is incredibly poisonous. One single hornet can easily kill hundreds of bees in just a few minutes. Most honeybees are completely defenseless against these massive killers. But one special kind of Japanese honeybee has discovered a brilliant military defense. Hornets absolutely cannot survive in temperatures higher than forty-six degrees Celsius. However, these special bees can survive up to forty-eight degrees. When the dangerous hornets enter their hive, the bees do not run away. Instead, hundreds of bees quickly surround the hornets. They make a tight ball around the enemies. Then, all the bees start shaking their wings violently at the exact same time. This intense movement rapidly raises the temperature inside the ball. The heat becomes trapped. Before the invading hornets even realize what is happening, they are cooked alive by the extreme heat. The smart bees use teamwork and body heat to completely destroy their giant enemies.",
        dict: { "giant": "dev", "terrible": "korkunç", "dangerous": "tehlikeli", "sting": "iğne/sokma", "incredibly": "inanılmaz derecede", "poisonous": "zehirli", "single": "tek", "easily": "kolayca", "kill": "öldürmek", "honeybees": "bal arıları", "completely": "tamamen", "defenseless": "savunmasız", "against": "karşı", "massive": "muazzam", "special": "özel", "discovered": "keşfetti", "brilliant": "harika/parlak", "survive": "hayatta kalmak", "absolutely": "kesinlikle", "higher than": "den daha yüksek", "however": "ancak", "enter": "girmek", "run away": "kaçmak", "instead": "yerine", "quickly": "hızlıca", "surround": "kuşatmak", "tight": "sıkı", "start": "başlamak", "shaking": "sallama", "violently": "şiddetle", "exact": "tam", "intense": "yoğun", "movement": "hareket", "rapidly": "hızla", "raises": "yükseltir", "trapped": "kapana kısılmış", "invading": "istila eden", "realize": "fark etmek", "happening": "oluyor", "cooked": "pişmiş", "alive": "canlı", "extreme": "aşırı", "smart": "akıllı", "destroy": "yok etmek" },
        questions: [ {q:"Are giant hornets dangerous?", a_en:"Yes", a_tr:"Evet"}, {q:"What do they eat?", a_en:"Baby bees", a_tr:"Bebek arılar"}, {q:"Can one hornet kill hundreds of bees?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the bees defenseless?", a_en:"No", a_tr:"Hayır"}, {q:"What is the hornet's survival temperature?", a_en:"Forty six", a_tr:"Kırk altı"}, {q:"What do the bees shake?", a_en:"Wings", a_tr:"Kanatlar"}, {q:"How are the hornets killed?", a_en:"Heat", a_tr:"Isı"} ]
    }],

    "13_GreedyGibbons.mp3": [{ 
        text: "Gibbons are very fast, agile monkeys. It is usually extremely difficult for hunters to catch them. Indonesia hunters found a simple way to trap them by using the monkey's own greed. They cut a small hole in a hard coconut. They put a sweet, delicious banana inside. A gibbon pushes its hand through the hole to grab the banana. But once it holds the fruit, its hand forms a large fist. The closed fist is completely trapped. It is too big to pull back through the small hole. To easily escape, the gibbon just needs to let go of the banana. But the monkey is incredibly greedy. It absolutely refuses to drop the food. Because of this foolish greed, the hunters easily walk up and catch the trapped monkey.",
        dict: { "fast": "hızlı", "agile": "çevik", "usually": "genellikle", "extremely": "son derece", "difficult": "zor", "catch": "yakalamak", "found": "buldu", "simple": "basit", "trap": "tuzak kurmak", "using": "kullanarak", "own": "kendi", "greed": "açgözlülük", "cut": "kesmek", "small": "küçük", "hard": "sert", "sweet": "tatlı", "delicious": "lezzetli", "pushes": "iter", "grab": "yakalamak", "once": "bir kez", "holds": "tutar", "forms": "oluşturur", "large": "büyük", "fist": "yumruk", "closed": "kapalı", "completely": "tamamen", "trapped": "kapana kısılmış", "big": "büyük", "easily": "kolayca", "escape": "kaçmak", "needs": "ihtiyaç duymak", "let go": "bırakmak", "incredibly": "inanılmaz derecede", "greedy": "açgözlü", "absolutely": "kesinlikle", "refuses": "reddeder", "drop": "düşürmek/bırakmak", "foolish": "aptalca", "walk up": "yürüyüp yaklaşmak" },
        questions: [ {q:"Where do gibbons live?", a_en:"Trees", a_tr:"Ağaçlar"}, {q:"Are they fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Where is the banana?", a_en:"Coconut", a_tr:"Hindistan cevizi"}, {q:"Does the gibbon use its hand?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the hand become a fist?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the monkey let go of the food?", a_en:"No", a_tr:"Hayır"}, {q:"Why is it caught?", a_en:"Greed", a_tr:"Açgözlülük"} ]
    }],

    "14_GrievingAnimals.mp3": [{ 
        text: "Scientists observed that two specific types of animals hold emotional funerals. One is the giant elephant, and the other is a smart bird called a jaybird. When an old elephant dies, the others refuse to leave the body. They carefully cover their dead friend with soft leaves, dirt, and branches. They stand quietly around the body for days and make deep, crying sounds to express their sadness. Jaybirds have a similar ritual. When a jaybird dies, the first bird makes a loud alarm call. nearby birds gather around. They collect dry sticks and green leaves to gently cover their friend's body. They completely stop flying and hunting for twenty-four hours. They stay together to mourn their loss. These beautiful, sad ceremonies are incredibly similar to human funerals and show deep emotional connections.",
        dict: { "observed": "gözlemledi", "specific": "belirli", "actually": "aslında", "hold": "tutmak/düzenlemek", "emotional": "duygusal", "funerals": "cenazeler", "dead": "ölü", "giant": "dev", "smart": "akıllı", "old": "yaşlı", "dies": "ölür", "refuse": "reddetmek", "leave": "ayrılmak", "carefully": "dikkatlice", "cover": "örtmek", "soft": "yumuşak", "stand": "durmak", "quietly": "sessizce", "deep": "derin", "crying": "ağlayan", "express": "ifade etmek", "sadness": "üzüntü", "similar": "benzer", "ritual": "ritüel", "loud": "yüksek sesli", "gather": "toplanmak", "completely": "tamamen", "collect": "toplamak", "dry": "kuru", "green": "yeşil", "gently": "nazikçe", "stop": "durdurmak", "stay": "kalmak", "mourn": "yas tutmak", "beautiful": "güzel", "incredibly": "inanılmaz derecede", "show": "göstermek" },
        questions: [ {q:"Do animals have funerals?", a_en:"Yes", a_tr:"Evet"}, {q:"Which big animal is mentioned?", a_en:"Elephant", a_tr:"Fil"}, {q:"What bird is mentioned?", a_en:"Jaybird", a_tr:"Alakarga"}, {q:"Do elephants cover the body?", a_en:"Yes", a_tr:"Evet"}, {q:"What sounds do they make?", a_en:"Crying", a_tr:"Ağlama"}, {q:"Do jaybirds stop hunting?", a_en:"Yes", a_tr:"Evet"}, {q:"How long do jaybirds mourn?", a_en:"Twenty four hours", a_tr:"Yirmi dört saat"} ]
    }],

    "15_NeighborLobsters.mp3": [{ 
        text: "Lobsters are usually very aggressive, solitary animals. They are absolutely not friendly with each other. Strong male lobsters often fight violently to protect their personal land. Sometimes, they even fight to the death to defend their borders. However, if a large predator comes to attack, the angry neighbor lobster immediately rushes over to help. They completely forget their old fights. They stand side by side and use their sharp claws to chase the big attacker away. After they successfully defeat the shared enemy, the two lobsters become respectful friends. They never fight each other again. They live peacefully as neighbors. Finally, when one of the lobsters dies, the surviving friend automatically takes control of the dead lobster's empty land. The other lobsters in the area respectfully accept this peaceful transfer of power without any new fights.",
        dict: { "usually": "genellikle", "aggressive": "agresif", "solitary": "yalnız yaşayan", "absolutely": "kesinlikle", "friendly": "arkadaş canlısı", "strong": "güçlü", "male": "erkek", "often": "sık sık", "fight": "savaşmak", "violently": "şiddetle", "protect": "korumak", "personal": "kişisel", "death": "ölüm", "defend": "savunmak", "large": "büyük", "comes": "gelir", "attack": "saldırmak", "angry": "öfkeli", "immediately": "derhal", "rushes": "koşar", "help": "yardım", "forget": "unutmak", "stand": "durmak", "side by side": "yan yana", "sharp": "keskin", "successfully": "başarıyla", "defeat": "yenmek", "shared": "paylaşılan", "enemy": "düşman", "become": "olmak", "respectful": "saygılı", "never": "asla", "peacefully": "huzurlu", "dies": "ölür", "surviving": "hayatta kalan", "automatically": "otomatik olarak", "accept": "kabul etmek" },
        questions: [ {q:"Are lobsters friendly first?", a_en:"No", a_tr:"Hayır"}, {q:"Do they live at the bottom?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they fight for land?", a_en:"Yes", a_tr:"Evet"}, {q:"Does a neighbor help?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they use claws?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they stay friends later?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they fight for the dead friend's land?", a_en:"No", a_tr:"Hayır"} ]
    }],

    "16_NepotistHyenas.mp3": [{ 
        text: "Hyenas are famous African scavengers. In a hyena pack, the females are always the absolute leaders. The most powerful alpha female completely controls the entire group. Everyone must strictly obey her rules. The alpha female strongly practices nepotism, which means she always favors her own family. She always gives the best food and privileges to her own children. Her babies get total protection because of their royal blood. Despite this unfair favoritism, the strict social order makes the group extremely dangerous. By working perfectly together, a large pack of hyenas can easily steal food from huge lions. If a lion tries to resist, the organized hyenas will violently attack and kill it.",
        dict: { "famous": "ünlü", "female": "dişi", "always": "her zaman", "absolute": "mutlak", "leaders": "liderler", "powerful": "güçlü", "completely": "tamamen", "controls": "kontrol eder", "strictly": "sıkıca", "obey": "itaat etmek", "strongly": "güçlü bir şekilde", "means": "anlamına gelir", "favors": "kayırır", "own": "kendi", "gives": "verir", "best": "en iyi", "children": "çocuklar", "total": "tam/toplam", "protection": "koruma", "royal": "kraliyet", "unfair": "adil olmayan", "strict": "sert", "order": "düzen", "extremely": "son derece", "dangerous": "tehlikeli", "working": "çalışma", "perfectly": "kusursuzca", "together": "birlikte", "easily": "kolayca", "steal": "çalmak", "huge": "kocaman", "resist": "direnmek", "organized": "organize", "violently": "şiddetle", "kill": "öldürmek" },
        questions: [ {q:"Are hyenas scavengers?", a_en:"Yes", a_tr:"Evet"}, {q:"Who are the leaders in a hyena pack?", a_en:"Females", a_tr:"Dişiler"}, {q:"Does the alpha female control the group?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the society fair?", a_en:"No", a_tr:"Hayır"}, {q:"Does she favor her family?", a_en:"Yes", a_tr:"Evet"}, {q:"Can they steal food from lions?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they work together?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "17_SlaveTraderAnts.mp3": [{ 
        text: "Amazon dangerous ants have long, sharp teeth. They use these teeth like deadly swords to easily kill their enemies. But the ants physically cannot chew their own food. The warrior ants march out and attack the peaceful nests of smaller ants. They ruthlessly kill all the adult defenders. Then, they steal the small ants' unhatched eggs. When these stolen eggs finally hatch, the young ants do not know they are kidnapped. Their natural instinct tells them to work hard. They go out, collect fresh food, and bring it back. Most importantly, they chew the food and feed it directly into the mouths of their cruel masters. When the killer ants grow strong again, they brutally execute all their loyal slaves.",
        dict: { "dangerous": "tehlikeli", "long": "uzun", "sharp": "keskin", "teeth": "dişler", "deadly": "ölümcül", "easily": "kolayca", "kill": "öldürmek", "enemies": "düşmanlar", "physically": "fiziksel olarak", "cannot": "yapamaz", "chew": "çiğnemek", "own": "kendi", "warrior": "savaşçı", "march out": "dışarı yürümek", "attack": "saldırmak", "peaceful": "huzurlu", "smaller": "daha küçük", "ruthlessly": "acımasızca", "steal": "çalmak", "hatch": "yumurtadan çıkmak", "finally": "sonunda", "know": "bilmek", "kidnapped": "kaçırılmış", "natural": "doğal", "work hard": "sıkı çalışmak", "collect": "toplamak", "fresh": "taze", "bring": "getirmek", "feed": "beslemek", "directly": "doğrudan", "cruel": "zalim", "strong": "güçlü", "again": "tekrar", "brutally": "acımasızca", "execute": "idam etmek", "loyal": "sadık" },
        questions: [ {q:"Where do these ants live?", a_en:"Amazon", a_tr:"Amazon"}, {q:"Are their teeth sharp?", a_en:"Yes", a_tr:"Evet"}, {q:"Can they chew their food?", a_en:"No", a_tr:"Hayır"}, {q:"Do they attack peaceful nests?", a_en:"Yes", a_tr:"Evet"}, {q:"What do they steal?", a_en:"Eggs", a_tr:"Yumurtalar"}, {q:"Do slave ants work hard?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they execute the slaves later?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "18_TraderGorillas.mp3": [{ 
        text: "Scientists conducted an economic experiment with four gorillas. Every morning, a researcher gave each gorilla some tokens. In the afternoon, they offered them cucumbers for tokens. One day, the researcher gave the first gorilla delicious grapes, but he only gave the others plain cucumbers. The three angry gorillas went on strike. They completely refused to hand over their tokens for boring cucumbers. They demanded the sweet grapes too. Finally, the researcher gave the first gorilla an amazing banana, and gave the others the grapes. The three gorillas were furious again! This time, they refused to give their tokens for grapes. They angrily demanded a banana. They perfectly understood unfair wages and learned how to trade their currency for the absolute best food.",
        dict: { "conducted": "yürüttü", "intelligent": "zeki", "gave": "verdi", "offered": "teklif etti", "plain": "sade", "delicious": "lezzetli", "grapes": "üzümler", "others": "diğerleri", "angry": "öfkeli", "went on strike": "greve gitti", "completely": "tamamen", "refused": "reddetti", "boring": "sıkıcı", "demanded": "talep etti", "sweet": "tatlı", "finally": "sonunda", "amazing": "harika", "furious": "öfkeli", "again": "tekrar", "angrily": "öfkeyle", "perfectly": "kusursuzca", "understood": "anladı", "unfair": "adil olmayan", "learned": "öğrendi", "best": "en iyi" },
        questions: [ {q:"How many gorillas were there?", a_en:"Four", a_tr:"Dört"}, {q:"What did they get in the morning?", a_en:"Tokens", a_tr:"Jetonlar"}, {q:"Did they like cucumbers first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the researcher change rules?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they go on strike?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they want sweet grapes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they want a banana in the end?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "19_TrickyPenguins.mp3": [{ 
        text: "Most penguins live in frozen, icy environments. Small stones are extremely valuable to them. They absolutely need these little stones to build safe, dry nests on the ice. If a female does not have a good nest, she cannot lay her precious eggs. Penguins stay loyal to one partner. However, some tricky female penguins have discovered a scandalous way to get extra stones. They approach young, single male penguins. They flirt and act like they want to mate. The excited young males quickly bring the females beautiful stones. But as soon as the tricky females get the stones, they immediately run away. They completely refuse to have any romantic contact, leaving the young males totally scammed and confused.",
        dict: { "frozen": "donmuş", "icy": "buzlu", "valuable": "değerli", "absolutely": "kesinlikle", "need": "ihtiyaç duymak", "build": "inşa etmek", "safe": "güvenli", "dry": "kuru", "cannot": "yapamaz", "lay": "koymak/yumurtlamak", "precious": "değerli", "stay": "kalmak", "loyal": "sadık", "tricky": "hileci", "discovered": "keşfetti", "scandalous": "skandal", "extra": "fazla", "approach": "yaklaşmak", "young": "genç", "single": "tek/yalnız", "flirt": "flört etmek", "excited": "heyecanlı", "quickly": "hızlıca", "bring": "getirmek", "immediately": "derhal", "run away": "kaçmak", "refuse": "reddetmek", "leaving": "bırakarak", "scammed": "dolandırılmış", "confused": "kafası karışmış" },
        questions: [ {q:"Where do penguins live?", a_en:"Icy environment", a_tr:"Buzlu ortam"}, {q:"Are there trees in the ice?", a_en:"No", a_tr:"Hayır"}, {q:"What is valuable to them?", a_en:"Stones", a_tr:"Taşlar"}, {q:"Do they need stones for nests?", a_en:"Yes", a_tr:"Evet"}, {q:"Are penguins generally loyal?", a_en:"Yes", a_tr:"Evet"}, {q:"Are some females tricky?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the tricky females stay for romance?", a_en:"No", a_tr:"Hayır"} ]
    }],

    "20_UrbanizedRaccoons.mp3": [{ 
        text: "Living in a modern city requires better problem-solving skills than a quiet forest. Many clever raccoons moved into cities because they found an easy way to eat. Instead of struggling to hunt, they steal delicious leftover food from human trash cans. Over time, these city raccoons learned exactly how to open complex, heavy lids. Scientists trapped some hungry wild raccoons and brought them into the city. The wild raccoons quickly smelled the food. However, they lacked the necessary urban skills. No matter how hard they pulled, they simply could not figure out how to open the complicated lids. Eventually, the frustrated forest raccoons gave up completely and ran back to the woods. This experiment proved that city raccoons evolve and develop advanced survival skills.",
        dict: { "modern": "modern", "requires": "gerektirir", "better": "daha iyi", "quiet": "sessiz", "clever": "zeki", "moved": "taşındı", "easy": "kolay", "struggling": "mücadele ederek", "hunt": "avlanmak", "steal": "çalmak", "delicious": "lezzetli", "leftover": "artık", "learned": "öğrendi", "exactly": "tam olarak", "open": "açmak", "complex": "karmaşık", "heavy": "ağır", "trapped": "yakaladı", "brought": "getirdi", "quickly": "hızlıca", "smelled": "kokladı", "lacked": "yoksun kaldı", "necessary": "gerekli", "simply": "basitçe", "figure out": "çözmek/anlamak", "eventually": "sonunda", "frustrated": "hüsrana uğramış", "gave up": "vazgeçti", "proved": "kanıtladı", "evolve": "evrilmek", "advanced": "gelişmiş" },
        questions: [ {q:"Is city life harder for raccoons?", a_en:"Yes", a_tr:"Evet"}, {q:"Where do clever raccoons move?", a_en:"Cities", a_tr:"Şehirler"}, {q:"What do they steal?", a_en:"Food", a_tr:"Yiyecek"}, {q:"Can city raccoons open lids?", a_en:"Yes", a_tr:"Evet"}, {q:"Can wild raccoons open city lids?", a_en:"No", a_tr:"Hayır"}, {q:"Do wild raccoons give up?", a_en:"Yes", a_tr:"Evet"}, {q:"Does city life force evolution?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "21_VulturesGroupWork.mp3": [{ 
        text: "Vultures are actually incredibly important for our environment. They act as nature's sanitation workers. They quickly eat dead animals so rotting meat does not spread terrible diseases. Vultures are masters of specialized group work. A large flock can completely eat a massive dead giraffe in three hours. They divide the labor perfectly. Older vultures eat the soft internal organs, while younger birds clean the hard bones. The biggest and strongest vultures stand in a circle around the food. They act as strict security guards to keep angry hyenas away. When the main group is finally full, the loyal guards step forward to eat their fair share. When they are finished, the dangerous dead animal is completely erased.",
        dict: { "actually": "aslında", "important": "önemli", "act": "davranmak", "quickly": "hızlıca", "dead": "ölü", "rotting": "çürüyen", "spread": "yaymak", "terrible": "korkunç", "disappear": "yok olmak", "deadly": "ölümcül", "sick": "hasta", "specialized": "uzmanlaşmış", "massive": "muazzam", "divide": "bölmek", "perfectly": "kusursuzca", "internal": "içsel", "clean": "temizlemek", "hard": "sert", "biggest": "en büyük", "strongest": "en güçlü", "stand": "durmak", "strict": "sert", "finally": "sonunda", "full": "tok", "loyal": "sadık", "finished": "bitmiş", "dangerous": "tehlikeli", "erased": "silinmiş" },
        questions: [ {q:"Are vultures important?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they eat live animals?", a_en:"No", a_tr:"Hayır"}, {q:"Do they spread disease?", a_en:"No", a_tr:"Hayır"}, {q:"Can they eat a giraffe quickly?", a_en:"Yes", a_tr:"Evet"}, {q:"Do older vultures eat the soft parts?", a_en:"Yes", a_tr:"Evet"}, {q:"Do guards keep jackals away?", a_en:"Yes", a_tr:"Evet"}, {q:"Do guards eat in the end?", a_en:"Yes", a_tr:"Evet"} ]
    }]
};
