const lessonData = {
    "01_AggressiveMonkeys.mp3": [{ 
        text: "Scientists wanted to see how a group learns violent rules. They put five chimpanzees in a cage. They hung delicious yellow bananas high up near the ceiling. When one monkey climbed up to get the bananas, scientists sprayed all five monkeys with very cold, uncomfortable water. After this happened a few times, the monkeys learned a new rule. The bananas caused the bad water. To stop the cold water, the group attacked any monkey that tried to reach the food. Then, the scientists changed the monkeys. They took one old monkey out and put a new monkey in. The new monkey didn't know about the cold water. It immediately tried to grab the bananas. The other four monkeys quickly attacked it and beat it up. The scientists slowly replaced all the original monkeys. Eventually, there were five completely new monkeys in the cage. The cold water was never used again. But whenever any monkey reached for the bananas, the group fiercely attacked it. The monkeys continued this violent behavior. They kept beating each other up simply because it was the established rule of their society. They followed the group rule blindly without knowing why it existed.",
        dict: { 
            "wanted": "istedi", "see": "görmek", "learns": "öğrenir", "violent": "şiddetli/zorba", "rules": "kurallar", "put": "koydu", "hung": "astı", "delicious": "lezzetli", "yellow": "sarı", "high": "yüksek", "near": "yakın", "climbed": "tırmandı", "get": "almak", "sprayed": "püskürttü", "cold": "soğuk", "uncomfortable": "rahatsız", "happened": "oldu/gerçekleşti", "few": "birkaç", "learned": "öğrendi", "new": "yeni", "caused": "sebep oldu", "bad": "kötü", "stop": "durdurmak", "attacked": "saldırdı", "tried": "denedi", "reach": "ulaşmak", "changed": "değiştirdi", "took": "aldı/çıkardı", "did not know": "bilmiyordu", "immediately": "derhal", "grab": "yakalamak", "other": "diğer", "quickly": "hızlıca", "beat up": "dövmek/hırpalamak", "slowly": "yavaşça", "replaced": "değiştirdi", "original": "orijinal/asıl", "eventually": "sonunda", "completely": "tamamen", "never": "asla", "used": "kullanıldı", "again": "tekrar", "whenever": "her ne zaman", "reached": "ulaştı", "fiercely": "şiddetle", "continued": "devam etti", "behavior": "davranış", "kept": "devam etti/sürdürdü", "beating": "dövme", "each other": "birbirlerini", "simply": "sadece/basitçe", "because": "çünkü", "established": "yerleşmiş/kurulmuş", "society": "toplum", "followed": "takip etti", "blindly": "körlemesine", "without": "olmaksızın", "knowing": "bilerek", "existed": "var oldu" 
        },
        questions: [ {q:"How many chimpanzees were in the cage?", a_en:"Five", a_tr:"Beş"}, {q:"What color were the bananas?", a_en:"Yellow", a_tr:"Sarı"}, {q:"What did scientists spray?", a_en:"Water", a_tr:"Su"}, {q:"Was the water cold?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the new monkeys know the rule?", a_en:"No", a_tr:"Hayır"}, {q:"Did they attack for bananas?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the rule followed blindly?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "02_AntSacrifice.mp3": [{ 
        text: "Ant colonies have a very strict society to survive dangerous times. Sometimes, there is absolutely no food available for the ants. The colony begins to starve and die. To save the group, one single ant will bravely sacrifice its own life. This special ant is always the oldest and weakest ant in the colony. Twenty young, strong warrior ants leave the nest with the old ant. They look for a tarantula, which is a huge, poisonous spider. When they find the spider, the young warrior ants hide behind rocks. The old ant slowly walks directly toward the dangerous spider. The hungry tarantula immediately sees the old ant and attacks. It uses all of its deadly poison to kill the single old ant. After the spider finishes its attack, it has no more poison left in its body. Suddenly, the twenty hiding warrior ants jump out. They easily attack and kill the defenseless spider. They carefully carry the giant spider's body back home to their hungry colony. Thanks to the brave sacrifice of the oldest ant, the whole colony gets enough food to survive the terrible shortage.",
        dict: { 
            "have": "sahip olmak", "strict": "sert/katı", "society": "toplum", "survive": "hayatta kalmak", "dangerous": "tehlikeli", "sometimes": "bazen", "absolutely": "kesinlikle", "available": "mevcut/bulunur", "begins": "başlar", "starve": "açlıktan ölmek", "die": "ölmek", "save": "kurtarmak", "single": "tek", "bravely": "cesurca", "sacrifice": "feda etmek", "own": "kendi", "special": "özel", "always": "her zaman", "oldest": "en yaşlı", "weakest": "en zayıf", "young": "genç", "strong": "güçlü", "leave": "ayrılmak", "look for": "aramak", "huge": "kocaman", "poisonous": "zehirli", "find": "bulmak", "hide": "saklanmak", "behind": "arkasında", "slowly": "yavaşça", "walks": "yürür", "directly": "doğrudan", "toward": "doğru", "hungry": "aç", "immediately": "derhal", "sees": "görür", "attacks": "saldırır", "uses": "kullanır", "deadly": "ölümcül", "kill": "öldürmek", "finishes": "bitirir", "left": "kalan", "suddenly": "aniden", "hiding": "saklanan", "jump out": "dışarı fırlamak", "easily": "kolayca", "defenseless": "savunmasız", "carefully": "dikkatlice", "carry": "taşımak", "giant": "dev", "back": "geri", "brave": "cesur", "whole": "bütün/tüm", "gets": "alır", "enough": "yeterli", "terrible": "korkunç", "shortage": "kıtlık" 
        },
        questions: [ {q:"Is ant society strict?", a_en:"Yes", a_tr:"Evet"}, {q:"Which ant is sacrificed?", a_en:"Oldest", a_tr:"En yaşlı"}, {q:"What animal do they look for?", a_en:"Tarantula", a_tr:"Tarantula"}, {q:"Is the spider poisonous?", a_en:"Yes", a_tr:"Evet"}, {q:"How many warrior ants hide?", a_en:"Twenty", a_tr:"Yirmi"}, {q:"Does the spider keep its poison?", a_en:"No", a_tr:"Hayır"}, {q:"Does the colony survive?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "03_BeeDemocracy.mp3": [{ 
        text: "Many people think only humans have elections, but some animals also use democratic systems. Honeybees are a perfect example of animal democracy. Even though the leader of the hive is called a queen, the bees make important decisions together. When their old hive gets too crowded, they need to build a new home. The scout bees explore different places. Then, they come back and vote on the best location by doing a special dance in the air. After they build the new hive, they must elect a brand new queen. They usually have three or four young candidates for the job. The bees hold a real, democratic election. The candidates try to get followers. The young bee with the most supporters officially becomes the new queen. The other bees do not fight or start a war over the results. They completely accept the new queen without any arguments. They respect the majority vote of the colony. This peaceful system helps the bees stay organized and strong. They show us that voting and accepting the final result is a very smart, natural way to successfully manage a large society.",
        dict: { 
            "think": "düşünmek", "only": "sadece", "have": "sahip olmak", "use": "kullanmak", "democratic": "demokratik", "perfect": "mükemmel", "democracy": "demokrasi", "leader": "lider", "called": "adlandırılan", "queen": "kraliçe", "make": "yapmak", "important": "önemli", "decisions": "kararlar", "together": "birlikte", "old": "eski", "crowded": "kalabalık", "need": "ihtiyaç duymak", "build": "inşa etmek", "new": "yeni", "explore": "keşfetmek", "different": "farklı", "come back": "geri gelmek", "vote": "oy vermek", "best": "en iyi", "special": "özel", "must": "zorunda olmak", "elect": "seçmek", "brand new": "yepyeni", "usually": "genellikle", "young": "genç", "candidates": "adaylar", "hold": "düzenlemek/tutmak", "real": "gerçek", "try": "denemek", "followers": "takipçiler", "supporters": "destekçiler", "officially": "resmen", "becomes": "olur", "other": "diğer", "fight": "savaşmak", "start": "başlatmak", "completely": "tamamen", "accept": "kabul etmek", "without": "olmaksızın", "arguments": "tartışmalar", "respect": "saygı duymak", "majority": "çoğunluk", "peaceful": "huzurlu", "helps": "yardım eder", "stay": "kalmak", "organized": "organize", "strong": "güçlü", "show": "göstermek", "final": "son", "smart": "akıllı", "natural": "doğal", "successfully": "başarıyla", "manage": "yönetmek", "large": "büyük", "society": "toplum" 
        },
        questions: [ {q:"Is a bee hive a democracy?", a_en:"Yes", a_tr:"Evet"}, {q:"What do scout bees do?", a_en:"Explore", a_tr:"Keşfetmek"}, {q:"How do bees vote?", a_en:"Dance", a_tr:"Dans"}, {q:"How many queen candidates?", a_en:"Four", a_tr:"Dört"}, {q:"Do the bees fight over results?", a_en:"No", a_tr:"Hayır"}, {q:"What does the system help?", a_en:"Organization", a_tr:"Organizasyon"}, {q:"Is voting natural for bees?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "04_BulletEatingSnakes.mp3": [{ 
        text: "In the wild animal world, having incredibly fast reflexes is usually a very good thing. Snakes are a great example. A snake's reaction time is extremely fast. It takes only a fraction of a second for them to react to danger. This makes them one of the absolute quickest animals in nature. However, sometimes being too fast and aggressive can actually be a terrible mistake. Imagine a cowboy riding a horse in the desert. Suddenly, a dangerous rattlesnake appears on the ground. The cowboy quickly pulls out his gun and shoots the snake. You might think the bullet is too fast for the snake. But here is the amazing truth: the snake's reflex is actually faster than the bullet. The snake clearly sees the fast bullet coming toward its head. Instead of moving away to save its life, the aggressive snake thinks the bullet is a small animal. It quickly tries to bite the bullet. Because of this angry reflex, the bullet goes straight into its mouth and kills it. If the snake simply moved out of the way, it would live. Its own aggressive reaction causes its tragic death.",
        dict: { 
            "wild": "vahşi", "having": "sahip olmak", "incredibly": "inanılmaz derecede", "fast": "hızlı", "reflexes": "refleksler", "usually": "genellikle", "good": "iyi", "great": "harika", "reaction": "reaksiyon", "extremely": "son derece", "takes": "alır", "react": "tepki vermek", "danger": "tehlike", "makes": "yapar", "absolute": "mutlak", "quickest": "en hızlı", "however": "ancak", "aggressive": "agresif", "actually": "aslında", "terrible": "korkunç", "mistake": "hata", "imagine": "hayal et", "riding": "binmek", "suddenly": "aniden", "dangerous": "tehlikeli", "appears": "görünür", "quickly": "hızlıca", "pulls out": "çıkarmak", "shoots": "ateş eder", "think": "düşünmek", "amazing": "şaşırtıcı", "truth": "gerçek", "faster": "daha hızlı", "clearly": "açıkça", "sees": "görür", "coming": "gelen", "toward": "doğru", "instead of": "yerine", "moving": "hareket etmek", "save": "kurtarmak", "thinks": "düşünür", "small": "küçük", "tries": "dener", "bite": "ısırmak", "angry": "öfkeli", "goes": "gider", "straight": "doğruca", "kills": "öldürür", "simply": "sadece/basitçe", "moved": "hareket etti", "live": "yaşamak", "own": "kendi", "causes": "sebep olur", "tragic": "trajik", "death": "ölüm" 
        },
        questions: [ {q:"Is a snake's reflex fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Where is the cowboy?", a_en:"Desert", a_tr:"Çöl"}, {q:"Does the cowboy shoot?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the reflex faster than the bullet?", a_en:"Yes", a_tr:"Evet"}, {q:"What does the snake think the bullet is?", a_en:"Animal", a_tr:"Hayvan"}, {q:"Where does the bullet go?", a_en:"Mouth", a_tr:"Ağız"}, {q:"Does the snake die?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "05_SealsAndDolphins.mp3": [{ 
        text: "Seals and dolphins live in the exact same ocean environment and eat the exact same kind of fish. However, they have completely different hunting strategies. Seals usually live together in large groups, but they act very selfishly. When a group of seals finds a lot of fish, every seal jumps into the water at the same time. They all try to aggressively catch as much food as possible for themselves. This crazy chaos scares the fish away quickly. Because of their selfish actions, the seals only catch a few fish. On the other hand, dolphins are incredibly smart and organized. When dolphins find fish, they work together as a perfect team. They swim in tight circles around the fish so the fish cannot escape. The weakest or youngest dolphins eat first. Then, they slowly switch places with the other dolphins. They take turns eating and swimming in circles. They continue this organized teamwork until every dolphin gets a fair share of food. If the greedy seals learned to work together patiently like the smart dolphins, they would easily catch much more food for their entire group.",
        dict: { 
            "live": "yaşamak", "exact": "tam/aynı", "same": "aynı", "eat": "yemek", "different": "farklı", "hunting": "avlanma", "usually": "genellikle", "together": "birlikte", "large": "büyük", "act": "davranmak", "selfishly": "bencilce", "finds": "bulur", "jumps": "atlar", "try": "denemek", "aggressively": "agresifçe", "catch": "yakalamak", "possible": "mümkün", "themselves": "kendileri", "crazy": "çılgın", "scares": "korkutur", "quickly": "hızlıca", "selfish": "bencil", "only": "sadece", "few": "az/birkaç", "smart": "akıllı", "organized": "organize", "work": "çalışmak", "perfect": "mükemmel", "swim": "yüzmek", "tight": "sıkı/dar", "around": "etrafında", "cannot": "yapamaz", "escape": "kaçmak", "weakest": "en zayıf", "youngest": "en genç", "first": "ilk", "slowly": "yavaşça", "switch": "değiştirmek", "places": "yerler", "take turns": "sırayla yapmak", "swimming": "yüzmek", "continue": "devam etmek", "until": "kadar", "gets": "alır", "fair": "adil", "greedy": "açgözlü", "learned": "öğrendi", "patiently": "sabırla", "easily": "kolayca", "entire": "tüm/bütün" 
        },
        questions: [ {q:"Do seals and dolphins eat fish?", a_en:"Yes", a_tr:"Evet"}, {q:"Are seals selfish?", a_en:"Yes", a_tr:"Evet"}, {q:"Do seals catch many fish?", a_en:"No", a_tr:"Hayır"}, {q:"Are dolphins organized?", a_en:"Yes", a_tr:"Evet"}, {q:"Who eats first in a dolphin group?", a_en:"Weakest", a_tr:"En zayıf"}, {q:"Do dolphins swim in circles?", a_en:"Yes", a_tr:"Evet"}, {q:"Are seals greedy?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "06_CleverOctopus.mp3": [{ 
        text: "Scientists believe the octopus is probably the most intelligent animal in the ocean. They did a special experiment to test animal intelligence. They took a very smart dog, a smart chimpanzee, and an octopus. They made all three animals very hungry. Then, they put delicious food inside a plastic bottle with a tight cap. The dog and the chimpanzee tried hard, but they could not open the bottle. They gave up after a few hours of trying. However, the clever octopus used its strong arms to unscrew the plastic cap. It opened the bottle in half an hour and ate the food. The next time the scientists gave the same bottle to the octopus, it opened the cap in only twenty seconds. But the most amazing part happened next. This smart octopus actually taught other octopuses how to open the bottles. Within three days, all the other octopuses easily opened their bottles in twenty seconds. Unfortunately, the average octopus only lives for about three short years. If these incredibly smart creatures lived much longer lives, they might build a complex, advanced civilization at the bottom of the sea.",
        dict: { 
            "believe": "inanmak", "probably": "muhtemelen", "most": "en", "intelligent": "zeki", "did": "yaptı", "special": "özel", "test": "test etmek", "took": "aldı", "smart": "akıllı", "made": "yaptı", "hungry": "aç", "put": "koydu", "delicious": "lezzetli", "inside": "içinde", "tight": "sıkı", "tried": "denedi", "hard": "zor/sıkı", "could not": "yapamadı", "open": "açmak", "gave up": "vazgeçti", "trying": "denemek", "clever": "zeki", "used": "kullandı", "strong": "güçlü", "unscrew": "vidayı açmak/çevirmek", "opened": "açtı", "ate": "yedi", "next": "gelecek/sonraki", "gave": "verdi", "same": "aynı", "only": "sadece", "amazing": "şaşırtıcı", "happened": "oldu", "actually": "aslında", "taught": "öğretti", "other": "diğer", "easily": "kolayca", "unfortunately": "maalesef", "average": "ortalama", "lives": "yaşar", "short": "kısa", "incredibly": "inanılmaz derecede", "longer": "daha uzun", "build": "inşa etmek", "complex": "karmaşık", "advanced": "gelişmiş", "bottom": "dip" 
        },
        questions: [ {q:"Which animal is most intelligent?", a_en:"Octopus", a_tr:"Ahtapot"}, {q:"What was inside the bottle?", a_en:"Food", a_tr:"Yiyecek"}, {q:"Did the dog open it?", a_en:"No", a_tr:"Hayır"}, {q:"How long did the octopus take first?", a_en:"Half hour", a_tr:"Yarım saat"}, {q:"How long the second time?", a_en:"Twenty seconds", a_tr:"Yirmi saniye"}, {q:"Did it teach others?", a_en:"Yes", a_tr:"Evet"}, {q:"How long do they live?", a_en:"Three years", a_tr:"Üç yıl"} ]
    }],

    "07_CrabMentality.mp3": [{ 
        text: "Just like some human beings, crabs often show a very negative and jealous behavior. When a single crab is put alone inside a basket, it can easily climb the sides. It quickly reaches the top and successfully escapes to freedom. However, the situation changes completely when there are two or more crabs in the same basket. When one brave crab tries to climb up toward the top, the other crabs become aggressive. They actively reach up and pull the climbing crab back down to the bottom. Instead of helping each other escape the trap, they constantly sabotage each other. Their internal jealousy makes sure that nobody ever escapes the basket. This strange behavior is incredibly reliable. Fishermen all over the world know about this natural habit. They never put a lid on their crab baskets because they know the crabs will happily keep each other trapped inside forever. This extremely self-defeating pattern created the famous human concept called \"crab mentality.\" It describes jealous people who try to pull down anyone who becomes successful, simply because they are envious of their progress.",
        dict: { 
            "show": "göstermek", "negative": "negatif", "jealous": "kıskanç", "single": "tek", "put": "konulmuş", "alone": "yalnız", "easily": "kolayca", "climb": "tırmanmak", "quickly": "hızlıca", "reaches": "ulaşır", "successfully": "başarıyla", "escapes": "kaçar", "changes": "değişir", "completely": "tamamen", "more": "daha fazla", "same": "aynı", "brave": "cesur", "tries": "dener", "toward": "doğru", "become": "olmak", "aggressive": "agresif", "actively": "aktifçe", "reach up": "yukarı uzanmak", "pull": "çekmek", "back down": "tekrar aşağı", "helping": "yardım etmek", "constantly": "sürekli", "sabotage": "sabotaj etmek", "internal": "içsel", "makes sure": "emin olur", "strange": "garip", "incredibly": "inanılmaz derecede", "reliable": "güvenilir", "know": "bilmek", "natural": "doğal", "never": "asla", "happily": "mutlulukla", "keep": "tutmak", "trapped": "kapana kısılmış", "forever": "sonsuza dek", "extremely": "son derece", "self-defeating": "kendine zarar veren", "created": "yarattı", "famous": "ünlü", "called": "adlandırılan", "describes": "tanımlar", "pull down": "aşağı çekmek", "becomes": "olur", "successful": "başarılı", "simply": "sadece", "envious": "kıskanç" 
        },
        questions: [ {q:"Can a single crab escape?", a_en:"Yes", a_tr:"Evet"}, {q:"Are crabs jealous?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they pull each other down?", a_en:"Yes", a_tr:"Evet"}, {q:"Do fishermen use lids?", a_en:"No", a_tr:"Hayır"}, {q:"Is this behavior reliable?", a_en:"Yes", a_tr:"Evet"}, {q:"What is the concept called?", a_en:"Crab mentality", a_tr:"Yengeç zihniyeti"}, {q:"Does jealousy stop progress?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "08_DogsInSubway.mp3": [{ 
        text: "Moscow is a very big city with a famous subway system. There are also about thirty-five thousand stray dogs living in the city. These dogs do not have homes or owners. Most of them live far away from the busy city center, in the quiet suburbs. But there is not enough food in the suburbs for all these hungry dogs. So, the smart dogs have learned to use the public subway trains. They clearly understand the different train lines and the daily schedules. Every morning, they enter the stations and take the train downtown with the human workers. They spend the day finding food in the busy city streets. In the evening, they take the correct train back to their quiet suburban homes. The people in Moscow are usually very nice to these smart dogs. The dogs have learned excellent public manners. They politely lie down on the floor between the passenger seats. They never bark loudly or bother anyone on the train. Because they are so quiet and polite, the humans never complain about sharing their morning commute with these amazing animal passengers.",
        dict: { 
            "famous": "ünlü", "stray": "başıboş", "living": "yaşayan", "have": "sahip olmak", "live": "yaşamak", "far away": "çok uzak", "busy": "meşgul", "quiet": "sessiz", "enough": "yeterli", "hungry": "aç", "smart": "akıllı", "learned": "öğrendi", "use": "kullanmak", "public": "kamu/halka açık", "clearly": "açıkça", "understand": "anlamak", "different": "farklı", "daily": "günlük", "enter": "girmek", "take": "almak/binmek", "spend": "geçirmek/harcamak", "finding": "bulma", "correct": "doğru", "usually": "genellikle", "nice": "nazik/iyi", "excellent": "mükemmel", "politely": "kibarca", "lie down": "uzanmak", "never": "asla", "bark": "havlamak", "loudly": "yüksek sesle", "bother": "rahatsız etmek", "polite": "kibar", "complain": "şikayet etmek", "sharing": "paylaşmak", "amazing": "şaşırtıcı" 
        },
        questions: [ {q:"In which city do the dogs live?", a_en:"Moscow", a_tr:"Moskova"}, {q:"How many stray dogs are there?", a_en:"Thirty five thousand", a_tr:"Otuz beş bin"}, {q:"Do they have owners?", a_en:"No", a_tr:"Hayır"}, {q:"Where do they live?", a_en:"Suburbs", a_tr:"Banliyöler"}, {q:"What do they use to go downtown?", a_en:"Subway", a_tr:"Metro"}, {q:"Are the dogs polite?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they bark on the train?", a_en:"No", a_tr:"Hayır"} ]
    }],

    "09_EmpathicMouse.mp3": [{ 
        text: "Many people think that only humans can understand the feelings of others. But scientists recently discovered that simple mice can actually feel empathy too. In an interesting experiment, scientists put one small mouse in a tight, uncomfortable cage. They made this mouse very hungry. Then, they put a second, free mouse into the same room. The free mouse saw the trapped animal. It immediately started trying to help. After some hard work, it finally opened the cage door and released the hungry mouse. The next day, the scientists repeated the exact same test. They put a brand new hungry mouse in the tight cage. Then, they brought back the very first mouse—the one that had been trapped the day before—and put it in the room. This mouse instantly ran to the cage. It quickly worked to set the new mouse free. It did this without any hesitation. The mouse clearly remembered the terrible feeling of being trapped and hungry. It felt genuine sadness for the new prisoner. This proves that animals can share emotional pain and actively try to help each other survive.",
        dict: { 
            "think": "düşünmek", "only": "sadece", "understand": "anlamak", "recently": "son zamanlarda", "discovered": "keşfetti", "simple": "basit", "actually": "aslında", "feel": "hissetmek", "interesting": "ilginç", "put": "koydu", "small": "küçük", "tight": "sıkı/dar", "uncomfortable": "rahatsız", "made": "yaptı", "hungry": "aç", "second": "ikinci", "free": "özgür", "same": "aynı", "saw": "gördü", "trapped": "kapana kısılmış", "immediately": "derhal", "started": "başladı", "trying": "deneme", "help": "yardım etmek", "hard": "zor/sıkı", "finally": "sonunda", "opened": "açtı", "released": "serbest bıraktı", "next": "gelecek/ertesi", "repeated": "tekrarladı", "exact": "tam/aynı", "brand new": "yepyeni", "brought back": "geri getirdi", "first": "ilk", "instantly": "anında", "ran": "koştu", "quickly": "hızlıca", "worked": "çalıştı", "without": "olmaksızın", "clearly": "açıkça", "remembered": "hatırladı", "terrible": "korkunç", "felt": "hissetti", "genuine": "gerçek/hakiki", "proves": "kanıtlar", "share": "paylaşmak", "emotional": "duygusal", "actively": "aktifçe", "try": "denemek", "survive": "hayatta kalmak" 
        },
        questions: [ {q:"Can mice feel empathy?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the cage comfortable?", a_en:"No", a_tr:"Hayır"}, {q:"Did the free mouse help?", a_en:"Yes", a_tr:"Evet"}, {q:"What did the free mouse open?", a_en:"Door", a_tr:"Kapı"}, {q:"Did the first mouse remember the feeling?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it hesitate to help?", a_en:"No", a_tr:"Hayır"}, {q:"Do mice share emotional pain?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "10_FearfulMice.mp3": [{ 
        text: "People often believe that mice are naturally born with a deep fear of cats. But in reality, this is not true. Mice actually learn this fear from their society, and the fear quickly spreads among them. Fear is a contagious emotion. Scientists did a test to prove this. They put a large, aggressive cat in a glass box. They put a laboratory mouse in another glass box next to it. When they opened the curtain, the angry cat tried to attack. The laboratory mouse showed absolutely no fear at all. It had never seen a cat in its entire life. Two hours later, the scientists put a wild street mouse next to the lab mouse. They opened the curtain again. The cat aggressively tried to catch them. The wild street mouse was terrified and quickly ran away to hide. Suddenly, the calm laboratory mouse also started running away in terror. The lab mouse learned to be afraid simply by watching the other mouse's panic. It learned the rules of survival and prejudice directly from its neighbor, proving that social fears are taught, not born.",
        dict: { 
            "often": "sık sık", "believe": "inanmak", "naturally": "doğal olarak", "born": "doğmuş", "deep": "derin", "true": "doğru", "actually": "aslında", "learn": "öğrenmek", "quickly": "hızlıca", "spreads": "yayılır", "contagious": "bulaşıcı", "did": "yaptı", "prove": "kanıtlamak", "put": "koydu", "large": "büyük", "aggressive": "agresif", "opened": "açtı", "angry": "öfkeli", "tried": "denedi", "attack": "saldırmak", "showed": "gösterdi", "absolutely": "kesinlikle", "seen": "görmüş", "entire": "tüm", "wild": "vahşi", "aggressively": "agresifçe", "catch": "yakalamak", "terrified": "dehşete düşmüş", "ran away": "kaçtı", "hide": "saklanmak", "suddenly": "aniden", "calm": "sakin", "started": "başladı", "running": "koşma", "learned": "öğrendi", "afraid": "korkmuş", "simply": "sadece", "watching": "izleyerek", "taught": "öğretildi" 
        },
        questions: [ {q:"Are mice born afraid of cats?", a_en:"No", a_tr:"Hayır"}, {q:"Is fear contagious?", a_en:"Yes", a_tr:"Evet"}, {q:"Where was the cat?", a_en:"Glass box", a_tr:"Cam kutu"}, {q:"Did the lab mouse feel fear first?", a_en:"No", a_tr:"Hayır"}, {q:"Who was next to the lab mouse later?", a_en:"Street mouse", a_tr:"Sokak faresi"}, {q:"Did the street mouse panic?", a_en:"Yes", a_tr:"Evet"}, {q:"Are social fears taught?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "11_FosterChildSquirrels.mp3": [{ 
        text: "In the animal kingdom, some animals love living in large groups, while others prefer to live completely alone. Canadian squirrels are solitary animals. This means they usually live by themselves in their own trees. Normally, animals that live alone are very selfish. They never allow strange animals to join their family or enter their territory. But female Canadian squirrels are incredibly different and special. Sometimes, baby squirrels lose their parents in the dangerous forest. When a female squirrel finds these poor, lonely orphans, she will bravely adopt them. She takes care of them like her own babies. The male squirrels are usually very angry about sharing their food, but the loving females persuade their partners to accept the new babies. This incredible kindness is never forgotten. When the orphaned babies grow up, they remember the mother who saved their lives. To show their deep gratitude, the young squirrels collect many extra nuts. They bring this extra food back to their foster mother as a beautiful way to say thank you for her love and protection.",
        dict: { 
            "love": "sevmek", "living": "yaşamak", "large": "büyük", "prefer": "tercih etmek", "completely": "tamamen", "alone": "yalnız", "solitary": "yalnız yaşayan", "means": "anlamına gelir", "usually": "genellikle", "own": "kendi", "normally": "normalde", "selfish": "bencil", "never": "asla", "allow": "izin vermek", "strange": "yabancı/garip", "join": "katılmak", "enter": "girmek", "female": "dişi", "incredibly": "inanılmaz derecede", "different": "farklı", "special": "özel", "sometimes": "bazen", "lose": "kaybetmek", "dangerous": "tehlikeli", "finds": "bulur", "poor": "fakir/zavallı", "lonely": "yalnız", "bravely": "cesurca", "adopt": "evlat edinmek", "takes care": "bakmak/ilgilenmek", "male": "erkek", "angry": "öfkeli", "sharing": "paylaşma", "loving": "sevgi dolu", "persuade": "ikna etmek", "accept": "kabul etmek", "new": "yeni", "incredible": "inanılmaz", "forgotten": "unutulmuş", "grow up": "büyümek", "remember": "hatırlamak", "saved": "kurtardı", "show": "göstermek", "deep": "derin", "young": "genç", "collect": "toplamak", "extra": "fazla", "bring": "getirmek", "beautiful": "güzel", "say": "söylemek" 
        },
        questions: [ {q:"Are Canadian squirrels social animals?", a_en:"No", a_tr:"Hayır"}, {q:"Do solitary animals usually share?", a_en:"No", a_tr:"Hayır"}, {q:"What do female squirrels find?", a_en:"Orphans", a_tr:"Yetimler"}, {q:"Who is angry about sharing food?", a_en:"Males", a_tr:"Erkekler"}, {q:"Is the kindness forgotten?", a_en:"No", a_tr:"Hayır"}, {q:"What do grown babies bring back?", a_en:"Nuts", a_tr:"Kuruyemişler"}, {q:"Is it a beautiful way to say thank you?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "12_FriedHornets.mp3": [{ 
        text: "Japanese Giant Hornets are terrible, dangerous insects. They love to attack honeybees and eat the soft baby bees. A hornet's sting is incredibly poisonous. One single hornet can easily kill hundreds of bees in just a few minutes. They attack the hive, kill the adults, and eat the babies. Most honeybees are completely defenseless against these massive killers. But one special kind of Japanese honeybee has discovered a brilliant military defense. Hornets absolutely cannot survive in temperatures higher than forty-six degrees Celsius. However, these special bees can survive up to forty-eight degrees. When the dangerous hornets enter their hive, the bees do not run away. Instead, hundreds of bees quickly surround the hornets. They make a tight ball around the enemies. Then, all the bees start shaking their wings violently at the exact same time. This intense movement rapidly raises the temperature inside the ball. The heat becomes trapped. Before the invading hornets even realize what is happening, they are cooked alive by the extreme heat. The smart bees use teamwork and body heat to completely destroy their giant enemies.",
        dict: { 
            "giant": "dev", "terrible": "korkunç", "dangerous": "tehlikeli", "love": "sevmek", "attack": "saldırmak", "eat": "yemek", "soft": "yumuşak", "incredibly": "inanılmaz derecede", "poisonous": "zehirli", "single": "tek", "easily": "kolayca", "kill": "öldürmek", "completely": "tamamen", "defenseless": "savunmasız", "massive": "muazzam", "special": "özel", "discovered": "keşfetti", "brilliant": "harika/parlak", "absolutely": "kesinlikle", "survive": "hayatta kalmak", "higher": "daha yüksek", "enter": "girmek", "run away": "kaçmak", "quickly": "hızlıca", "surround": "kuşatmak", "make": "yapmak", "tight": "sıkı", "start": "başlamak", "shaking": "sallama/titreme", "violently": "şiddetle", "exact": "tam", "same": "aynı", "intense": "yoğun", "rapidly": "hızla", "raises": "yükseltir", "becomes": "olur", "trapped": "kapana kısılmış", "invading": "istila eden", "realize": "fark etmek", "happening": "oluyor", "cooked": "pişmiş", "alive": "canlı", "extreme": "aşırı", "smart": "akıllı", "use": "kullanmak", "destroy": "yok etmek" 
        },
        questions: [ {q:"Are giant hornets dangerous?", a_en:"Yes", a_tr:"Evet"}, {q:"What do they eat?", a_en:"Baby bees", a_tr:"Bebek arılar"}, {q:"Can one hornet kill hundreds of bees?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the bees defenseless?", a_en:"No", a_tr:"Hayır"}, {q:"What is the hornet's survival temperature?", a_en:"Forty six", a_tr:"Kırk altı"}, {q:"What do the bees shake?", a_en:"Wings", a_tr:"Kanatlar"}, {q:"How are the hornets killed?", a_en:"Heat", a_tr:"Isı"} ]
    }],

    "13_GreedyGibbons.mp3": [{ 
        text: "Gibbons are very fast, agile monkeys that live high in the trees. It is usually extremely difficult for hunters to catch them. However, clever people in Indonesia have found a very simple way to trap them by using the monkey's own greed. Hunters sell these gibbons to foreign zoos to make good money. To catch them, the hunters cut a small hole in a hard coconut. They put a sweet, delicious banana inside and tie the coconut firmly to a tree. Gibbons have an excellent sense of smell. They quickly come down to get the tasty fruit. A gibbon pushes its small, open hand through the hole to grab the banana. But once it holds the fruit, its hand forms a large fist. The closed fist is completely trapped. It is too big to pull back through the small hole. To easily escape, the gibbon just needs to let go of the banana. But the monkey is incredibly greedy. It absolutely refuses to drop the food. Because of this foolish greed, the hunters easily walk up and catch the trapped monkey.",
        dict: { 
            "fast": "hızlı", "agile": "çevik", "live": "yaşamak", "high": "yüksek", "usually": "genellikle", "extremely": "son derece", "difficult": "zor", "catch": "yakalamak", "clever": "zeki", "found": "buldu", "simple": "basit", "trap": "tuzak kurmak", "using": "kullanarak", "own": "kendi", "sell": "satmak", "foreign": "yabancı", "make": "yapmak/kazanmak", "good": "iyi", "cut": "kesmek", "small": "küçük", "hard": "sert", "put": "koymak", "sweet": "tatlı", "delicious": "lezzetli", "tie": "bağlamak", "firmly": "sıkıca", "have": "sahip olmak", "excellent": "mükemmel", "quickly": "hızlıca", "come down": "aşağı inmek", "get": "almak", "tasty": "lezzetli", "pushes": "iter", "open": "açık", "grab": "yakalamak", "holds": "tutar", "forms": "oluşturur", "large": "büyük", "closed": "kapalı", "completely": "tamamen", "trapped": "kapana kısılmış", "big": "büyük", "pull back": "geri çekmek", "easily": "kolayca", "escape": "kaçmak", "needs": "ihtiyaç duymak", "let go": "bırakmak", "incredibly": "inanılmaz derecede", "greedy": "açgözlü", "absolutely": "kesinlikle", "refuses": "reddeder", "drop": "düşürmek/bırakmak", "foolish": "aptalca", "walk up": "yürüyüp yaklaşmak" 
        },
        questions: [ {q:"Where do gibbons live?", a_en:"Trees", a_tr:"Ağaçlar"}, {q:"Are they fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Where is the banana?", a_en:"Coconut", a_tr:"Hindistan cevizi"}, {q:"Does the gibbon use its hand?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the hand become a fist?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the monkey let go of the food?", a_en:"No", a_tr:"Hayır"}, {q:"Why is it caught?", a_en:"Greed", a_tr:"Açgözlülük"} ]
    }],

    "14_GrievingAnimals.mp3": [{ 
        text: "Many people believe that only humans understand the sad concept of death. But scientists have observed that two specific types of animals actually hold emotional funerals for their dead friends. One is the giant elephant, and the other is a smart bird called a jaybird. When an old elephant finally dies, the other elephants in the family refuse to leave the body. They carefully cover their dead friend with soft leaves, dirt, and branches. They stand quietly around the body for days and make deep, crying sounds to express their sadness. Jaybirds have a very similar ritual. When a jaybird dies, the first bird to find it makes a loud alarm call. This tells all the nearby birds to gather around. They fly down and completely surround the dead bird. They collect small, dry sticks and green leaves to gently cover their friend's body. They completely stop flying and hunting for food for twenty-four hours. They stay together to mourn their loss. These beautiful, sad ceremonies are incredibly similar to human funerals and show deep emotional connections.",
        dict: { 
            "believe": "inanmak", "only": "sadece", "understand": "anlamak", "sad": "üzgün", "observed": "gözlemledi", "specific": "belirli", "actually": "aslında", "hold": "düzenlemek/tutmak", "emotional": "duygusal", "dead": "ölü", "giant": "dev", "other": "diğer", "smart": "akıllı", "called": "adlandırılan", "old": "yaşlı", "finally": "sonunda", "dies": "ölür", "refuse": "reddetmek", "leave": "ayrılmak", "carefully": "dikkatlice", "cover": "örtmek", "soft": "yumuşak", "stand": "durmak", "quietly": "sessizce", "make": "yapmak", "deep": "derin", "crying": "ağlayan", "express": "ifade etmek", "similar": "benzer", "first": "ilk", "find": "bulmak", "loud": "yüksek sesli", "tells": "söyler", "nearby": "yakındaki", "gather": "toplanmak", "fly down": "aşağı uçmak", "completely": "tamamen", "surround": "kuşatmak", "collect": "toplamak", "small": "küçük", "dry": "kuru", "green": "yeşil", "gently": "nazikçe", "stop": "durdurmak", "flying": "uçmak", "hunting": "avlanmak", "stay": "kalmak", "together": "birlikte", "mourn": "yas tutmak", "beautiful": "güzel", "incredibly": "inanılmaz derecede", "show": "göstermek" 
        },
        questions: [ {q:"Do animals have funerals?", a_en:"Yes", a_tr:"Evet"}, {q:"Which big animal is mentioned?", a_en:"Elephant", a_tr:"Fil"}, {q:"What bird is mentioned?", a_en:"Jaybird", a_tr:"Alakarga"}, {q:"Do elephants cover the body?", a_en:"Yes", a_tr:"Evet"}, {q:"What sounds do they make?", a_en:"Crying", a_tr:"Ağlama"}, {q:"Do jaybirds stop hunting?", a_en:"Yes", a_tr:"Evet"}, {q:"How long do jaybirds mourn?", a_en:"Twenty four hours", a_tr:"Yirmi dört saat"} ]
    }],

    "15_NeighborLobsters.mp3": [{ 
        text: "Lobsters are usually very aggressive, solitary animals that live alone at the bottom of the sea. They are absolutely not friendly with each other. Strong male lobsters often fight violently to protect their personal land. Sometimes, they even fight to the death to defend their borders. However, their behavior completely changes when a foreign danger appears. If a large predator comes to attack one of the lobsters, the angry neighbor lobster immediately rushes over to help. They completely forget their old fights. They stand side by side and use their sharp claws to chase the big attacker away. After they successfully defeat the shared enemy, the two lobsters become respectful friends. They never fight each other over territory again for the rest of their lives. They live peacefully as neighbors. Finally, when one of the lobsters dies of old age, the surviving friend automatically takes control of the dead lobster's empty land. The other lobsters in the area respectfully accept this peaceful transfer of power without any new fights.",
        dict: { 
            "usually": "genellikle", "aggressive": "agresif", "solitary": "yalnız yaşayan", "live": "yaşamak", "alone": "yalnız", "absolutely": "kesinlikle", "friendly": "arkadaş canlısı", "strong": "güçlü", "male": "erkek", "often": "sık sık", "fight": "savaşmak/dövüşmek", "violently": "şiddetle", "protect": "korumak", "personal": "kişisel", "sometimes": "bazen", "defend": "savunmak", "completely": "tamamen", "changes": "değişir", "foreign": "yabancı", "appears": "görünür", "large": "büyük", "comes": "gelir", "attack": "saldırmak", "angry": "öfkeli", "immediately": "derhal", "rushes": "koşar/atılır", "help": "yardım etmek", "forget": "unutmak", "old": "eski", "stand": "durmak", "use": "kullanmak", "sharp": "keskin", "chase": "kovalamak", "big": "büyük", "successfully": "başarıyla", "defeat": "yenmek", "shared": "paylaşılan", "become": "olmak", "respectful": "saygılı", "never": "asla", "peacefully": "huzurla", "finally": "sonunda", "dies": "ölür", "surviving": "hayatta kalan", "automatically": "otomatik olarak", "takes": "alır", "empty": "boş", "other": "diğer", "respectfully": "saygıyla", "accept": "kabul etmek", "peaceful": "huzurlu", "new": "yeni" 
        },
        questions: [ {q:"Are lobsters friendly first?", a_en:"No", a_tr:"Hayır"}, {q:"Do they live at the bottom?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they fight for land?", a_en:"Yes", a_tr:"Evet"}, {q:"Does a neighbor help?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they use claws?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they stay friends later?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they fight for the dead friend's land?", a_en:"No", a_tr:"Hayır"} ]
    }],

    "16_NepotistHyenas.mp3": [{ 
        text: "Hyenas are famous African scavengers that often eat the leftover meat from larger predators. Their society is very different from many other animal groups. In a hyena pack, the females are always the absolute leaders. The most powerful, aggressive alpha female completely controls the entire group, and everyone must strictly obey her rules. The male hyenas peacefully accept their lower rank in the society. However, the pack is not a fair place. The alpha female strongly practices nepotism, which means she always favors her own family. She always gives the best food and privileges to her own children, even if other hyenas are much stronger or smarter. Her babies get total protection simply because of their royal blood. Despite this unfair favoritism, the strict social order makes the group extremely dangerous. By working perfectly together under the female leader's command, a large pack of hyenas can easily steal food from huge lions. If a lion tries to resist, the organized hyenas will violently attack and kill it.",
        dict: { 
            "famous": "ünlü", "often": "sık sık", "eat": "yemek", "leftover": "artık", "larger": "daha büyük", "different": "farklı", "many": "birçok", "other": "diğer", "female": "dişi", "always": "her zaman", "absolute": "mutlak", "powerful": "güçlü", "aggressive": "agresif", "completely": "tamamen", "controls": "kontrol eder", "entire": "tüm", "must": "zorunda olmak", "strictly": "sıkıca/kesinlikle", "obey": "itaat etmek", "male": "erkek", "peacefully": "huzurla", "accept": "kabul etmek", "lower": "daha düşük", "fair": "adil", "strongly": "güçlü bir şekilde", "practices": "uygular", "means": "anlamına gelir", "favors": "kayırır", "own": "kendi", "gives": "verir", "best": "en iyi", "stronger": "daha güçlü", "smarter": "daha zeki", "get": "alır", "total": "tam/toplam", "simply": "sadece", "royal": "kraliyet", "unfair": "adil olmayan", "strict": "sert", "makes": "yapar", "extremely": "son derece", "dangerous": "tehlikeli", "working": "çalışma", "perfectly": "kusursuzca", "together": "birlikte", "large": "büyük", "easily": "kolayca", "steal": "çalmak", "huge": "kocaman", "tries": "dener", "resist": "direnmek", "organized": "organize", "violently": "şiddetle", "attack": "saldırmak", "kill": "öldürmek" 
        },
        questions: [ {q:"Are hyenas scavengers?", a_en:"Yes", a_tr:"Evet"}, {q:"Who are the leaders in a hyena pack?", a_en:"Females", a_tr:"Dişiler"}, {q:"Does the alpha female control the group?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the society fair?", a_en:"No", a_tr:"Hayır"}, {q:"Does she favor her family?", a_en:"Yes", a_tr:"Evet"}, {q:"Can they steal food from lions?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they work together?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "17_SlaveTraderAnts.mp3": [{ 
        text: "Deep in the Amazon jungle, there is a very cruel and aggressive type of ant. These dangerous ants have long, sharp teeth outside their mouths. They use these teeth like deadly swords to easily kill their enemies in battle. But these long teeth create a massive problem: the ants physically cannot chew their own food. To solve this problem, they developed a terrible, imperialistic strategy. The warrior ants march out and attack the peaceful nests of smaller, weaker ants. They ruthlessly kill all the adult defenders. Then, they steal the small ants' unhatched eggs and carry them back to their own nest. When these stolen eggs finally hatch, the young ants do not know they are kidnapped. Their natural instinct tells them to work hard. They go out, collect fresh food, and bring it back. Most importantly, they chew the food and feed it directly into the mouths of their cruel masters. When the killer ants grow strong again, they brutally execute all their loyal slaves and march out to attack a brand new nest.",
        dict: { 
            "deep": "derin", "cruel": "zalim", "aggressive": "agresif", "dangerous": "tehlikeli", "have": "sahip olmak", "long": "uzun", "sharp": "keskin", "use": "kullanmak", "deadly": "ölümcül", "easily": "kolayca", "kill": "öldürmek", "create": "yaratmak", "massive": "muazzam", "physically": "fiziksel olarak", "cannot": "yapamaz", "chew": "çiğnemek", "own": "kendi", "solve": "çözmek", "developed": "geliştirdi", "terrible": "korkunç", "imperialistic": "emperyalist", "march out": "dışarı yürümek", "attack": "saldırmak", "peaceful": "huzurlu", "smaller": "daha küçük", "weaker": "daha zayıf", "ruthlessly": "acımasızca", "adult": "yetişkin", "steal": "çalmak", "unhatched": "yumurtadan çıkmamış", "carry": "taşımak", "stolen": "çalınmış", "finally": "sonunda", "hatch": "yumurtadan çıkmak", "young": "genç", "know": "bilmek", "kidnapped": "kaçırılmış", "natural": "doğal", "tells": "söyler", "work": "çalışmak", "hard": "sıkı", "go out": "dışarı çıkmak", "collect": "toplamak", "fresh": "taze", "bring": "getirmek", "feed": "beslemek", "directly": "doğrudan", "grow": "büyümek", "strong": "güçlü", "again": "tekrar", "brutally": "acımasızca", "execute": "idam etmek/öldürmek", "loyal": "sadık", "brand new": "yepyeni" 
        },
        questions: [ {q:"Where do these ants live?", a_en:"Amazon", a_tr:"Amazon"}, {q:"Are their teeth sharp?", a_en:"Yes", a_tr:"Evet"}, {q:"Can they chew their food?", a_en:"No", a_tr:"Hayır"}, {q:"Do they attack peaceful nests?", a_en:"Yes", a_tr:"Evet"}, {q:"What do they steal?", a_en:"Eggs", a_tr:"Yumurtalar"}, {q:"Do slave ants work hard?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they execute the slaves later?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "18_TraderGorillas.mp3": [{ 
        text: "Scientists conducted a fascinating economic experiment with four intelligent gorillas. The gorillas lived in four separate cages inside a large room. Every morning, a researcher gave each gorilla some plastic tokens. In the afternoon, another researcher offered them plain cucumbers and collected their tokens in exchange. The gorillas happily accepted this simple trade. One day, the researcher changed the rules. He gave the first gorilla delicious, sweet grapes for its tokens, but he only gave the other three gorillas the plain cucumbers. The next day, the three angry gorillas went on strike. They completely refused to hand over their tokens for boring cucumbers. They demanded the sweet grapes too. Finally, the researcher gave the first gorilla an amazing, tasty banana, and gave the other three the grapes. The three gorillas were furious again! This time, they refused to give their tokens for grapes. They angrily demanded a banana for their money. They perfectly understood the concept of unfair wages and learned how to aggressively trade their currency for the absolute best possible food.",
        dict: { 
            "conducted": "yürüttü/yaptı", "fascinating": "büyüleyici", "economic": "ekonomik", "intelligent": "zeki", "lived": "yaşadı", "separate": "ayrı", "large": "büyük", "gave": "verdi", "plastic": "plastik", "another": "diğer", "offered": "teklif etti", "plain": "sade", "collected": "topladı", "happily": "mutlulukla", "accepted": "kabul etti", "simple": "basit", "changed": "değiştirdi", "first": "ilk", "delicious": "lezzetli", "sweet": "tatlı", "only": "sadece", "other": "diğer", "next": "gelecek/ertesi", "angry": "öfkeli", "went": "gitti", "completely": "tamamen", "refused": "reddetti", "hand over": "teslim etmek", "boring": "sıkıcı", "demanded": "talep etti", "finally": "sonunda", "amazing": "harika", "tasty": "lezzetli", "furious": "öfkeli", "again": "tekrar", "angrily": "öfkeyle", "perfectly": "kusursuzca", "understood": "anladı", "unfair": "adil olmayan", "learned": "öğrendi", "aggressively": "agresifçe", "trade": "takas etmek/ticaret", "absolute": "mutlak", "best": "en iyi", "possible": "mümkün" 
        },
        questions: [ {q:"How many gorillas were there?", a_en:"Four", a_tr:"Dört"}, {q:"What did they get in the morning?", a_en:"Tokens", a_tr:"Jetonlar"}, {q:"Did they like cucumbers first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the researcher change rules?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they go on strike?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they want sweet grapes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they want a banana in the end?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "19_TrickyPenguins.mp3": [{ 
        text: "Most penguins live in completely frozen, icy environments. Because there are no trees or grass, small, smooth stones are extremely valuable to them. They absolutely need these little stones to build safe, dry nests on the ice. If a female penguin does not have a good stone nest, she cannot lay her precious eggs. Therefore, gathering stones is a matter of life and death. Penguins are generally monogamous animals, which means they stay loyal to one single partner. However, some very clever and tricky female penguins have discovered a scandalous way to get extra stones. While their loyal husbands are away hunting for fish, these females approach young, single male penguins. They flirt with the males and act like they want to mate. The excited young males quickly bring the females beautiful stones as romantic gifts. But as soon as the tricky females get the valuable stones, they immediately run away. They completely refuse to have any romantic contact, leaving the young males totally scammed and confused.",
        dict: { 
            "most": "çoğu", "live": "yaşamak", "completely": "tamamen", "frozen": "donmuş", "icy": "buzlu", "small": "küçük", "smooth": "pürüzsüz", "extremely": "son derece", "valuable": "değerli", "absolutely": "kesinlikle", "need": "ihtiyaç duymak", "little": "küçük", "build": "inşa etmek", "safe": "güvenli", "dry": "kuru", "female": "dişi", "have": "sahip olmak", "good": "iyi", "cannot": "yapamaz", "lay": "yumurtlamak", "precious": "değerli", "gathering": "toplama", "generally": "genellikle", "monogamous": "tek eşli", "means": "anlamına gelir", "stay": "kalmak", "loyal": "sadık", "single": "tek/yalnız", "clever": "zeki", "tricky": "hileci/kurnaz", "discovered": "keşfetti", "scandalous": "skandal", "get": "almak", "extra": "fazla", "away": "uzakta", "hunting": "avlanma", "approach": "yaklaşmak", "young": "genç", "male": "erkek", "flirt": "flört etmek", "act": "davranmak", "want": "istemek", "mate": "eşleşmek/çiftleşmek", "excited": "heyecanlı", "quickly": "hızlıca", "bring": "getirmek", "beautiful": "güzel", "romantic": "romantik", "immediately": "derhal", "run away": "kaçmak", "refuse": "reddetmek", "leaving": "bırakarak", "totally": "tamamen", "scammed": "dolandırılmış", "confused": "kafası karışmış" 
        },
        questions: [ {q:"Where do penguins live?", a_en:"Icy environment", a_tr:"Buzlu ortam"}, {q:"Are there trees in the ice?", a_en:"No", a_tr:"Hayır"}, {q:"What is valuable to them?", a_en:"Stones", a_tr:"Taşlar"}, {q:"Do they need stones for nests?", a_en:"Yes", a_tr:"Evet"}, {q:"Are penguins generally loyal?", a_en:"Yes", a_tr:"Evet"}, {q:"Are some females tricky?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the tricky females stay for romance?", a_en:"No", a_tr:"Hayır"} ]
    }],

    "20_UrbanizedRaccoons.mp3": [{ 
        text: "Living in a modern city requires much better problem-solving skills than living in a quiet forest. This rule applies perfectly to raccoons. Many clever raccoons have moved into human cities because they found an incredibly easy way to eat. Instead of struggling to hunt wild animals, they just steal delicious leftover food from human trash cans. Over time, these city raccoons have learned exactly how to open complex, heavy lids to reach the garbage. Scientists wanted to test their intelligence. They trapped some hungry wild raccoons from the deep forest and brought them into the city. The wild raccoons quickly smelled the food inside the city trash cans. However, they lacked the necessary urban skills. No matter how hard they pulled and scratched, they simply could not figure out how to open the complicated lids. Eventually, the frustrated forest raccoons gave up completely and ran back to the woods to hunt bugs. This experiment proved that the difficult urban environment forces city raccoons to evolve and develop highly advanced survival skills.",
        dict: { 
            "living": "yaşama", "modern": "modern", "requires": "gerektirir", "better": "daha iyi", "quiet": "sessiz", "applies": "uygulanır", "perfectly": "kusursuzca", "clever": "zeki", "moved": "taşındı", "human": "insan", "found": "buldu", "incredibly": "inanılmaz derecede", "easy": "kolay", "eat": "yemek", "struggling": "mücadele ederek", "hunt": "avlanmak", "wild": "vahşi", "steal": "çalmak", "delicious": "lezzetli", "learned": "öğrendi", "exactly": "tam olarak", "open": "açmak", "complex": "karmaşık", "heavy": "ağır", "reach": "ulaşmak", "wanted": "istedi", "test": "test etmek", "trapped": "yakaladı", "hungry": "aç", "deep": "derin", "brought": "getirdi", "quickly": "hızlıca", "smelled": "kokladı", "lacked": "yoksun kaldı", "necessary": "gerekli", "urban": "kentsel", "hard": "zor/sıkı", "pulled": "çekti", "scratched": "tırmaladı", "simply": "basitçe", "could not": "yapamadı", "figure out": "çözmek/anlamak", "complicated": "karmaşık", "eventually": "sonunda", "frustrated": "hüsrana uğramış", "gave up": "vazgeçti", "completely": "tamamen", "ran": "koştu", "proved": "kanıtladı", "difficult": "zor", "forces": "zorlar", "evolve": "evrimleşmek", "develop": "geliştirmek", "highly": "yüksek derecede", "advanced": "gelişmiş" 
        },
        questions: [ {q:"Is city life harder for raccoons?", a_en:"Yes", a_tr:"Evet"}, {q:"Where do clever raccoons move?", a_en:"Cities", a_tr:"Şehirler"}, {q:"What do they steal?", a_en:"Food", a_tr:"Yiyecek"}, {q:"Can city raccoons open lids?", a_en:"Yes", a_tr:"Evet"}, {q:"Can wild raccoons open city lids?", a_en:"No", a_tr:"Hayır"}, {q:"Do wild raccoons give up?", a_en:"Yes", a_tr:"Evet"}, {q:"Does city life force evolution?", a_en:"Yes", a_tr:"Evet"} ]
    }],

    "21_VulturesGroupWork.mp3": [{ 
        text: "Most people think vultures are ugly, gross birds, but they are actually incredibly important for our natural environment. They act as nature's sanitation workers. They quickly eat dead animals so the rotting meat does not spread terrible diseases. In places where vultures disappear, deadly bacteria grow and make local human populations very sick. Vultures are masters of specialized group work. A large flock can completely eat a massive dead giraffe in less than three hours. They divide the labor perfectly. The older, experienced vultures eat the soft internal organs, while the younger birds clean the hard bones. While the main group safely eats, the biggest and strongest vultures stand in a circle around the food. They act as strict security guards to keep angry hyenas and jackals away. When the main group is finally full, the loyal guards step forward to eat their fair share of the meat. When they are finished, the dangerous dead animal is completely erased from the environment.",
        dict: { 
            "think": "düşünmek", "ugly": "çirkin", "gross": "iğrenç", "actually": "aslında", "incredibly": "inanılmaz derecede", "important": "önemli", "natural": "doğal", "act": "davranmak", "quickly": "hızlıca", "eat": "yemek", "dead": "ölü", "rotting": "çürüyen", "spread": "yaymak", "terrible": "korkunç", "disappear": "yok olmak", "deadly": "ölümcül", "grow": "büyümek", "make": "yapmak", "local": "yerel", "sick": "hasta", "specialized": "uzmanlaşmış", "large": "büyük", "completely": "tamamen", "massive": "muazzam", "divide": "bölmek", "perfectly": "kusursuzca", "older": "daha yaşlı", "experienced": "tecrübeli", "soft": "yumuşak", "internal": "içsel", "younger": "daha genç", "clean": "temizlemek", "hard": "sert", "main": "ana/temel", "safely": "güvenle", "biggest": "en büyük", "strongest": "en güçlü", "stand": "durmak", "strict": "sert", "keep": "tutmak", "angry": "öfkeli", "finally": "sonunda", "full": "tok/dolu", "loyal": "sadık", "step forward": "öne çıkmak", "fair": "adil", "finished": "bitmiş", "dangerous": "tehlikeli", "erased": "silinmiş" 
        },
        questions: [ {q:"Are vultures important?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they eat live animals?", a_en:"No", a_tr:"Hayır"}, {q:"Do they spread disease?", a_en:"No", a_tr:"Hayır"}, {q:"Can they eat a giraffe quickly?", a_en:"Yes", a_tr:"Evet"}, {q:"Do older vultures eat the soft parts?", a_en:"Yes", a_tr:"Evet"}, {q:"Do guards keep jackals away?", a_en:"Yes", a_tr:"Evet"}, {q:"Do guards eat in the end?", a_en:"Yes", a_tr:"Evet"} ]
    }]
};
